# Generated by Django 5.0.6 on 2025-12-12 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZDAB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CODE', models.CharField(help_text='3 lettres majuscules (ex: CPN, RTT, MAL)', max_length=3, unique=True, verbose_name='Code absence')),
                ('LIBELLE', models.CharField(max_length=100, verbose_name="Libellé du type d'absence")),
                ('STATUT', models.BooleanField(default=True, verbose_name='Statut actif')),
            ],
            options={
                'verbose_name': "Type d'Absence",
                'verbose_name_plural': "Types d'Absence",
                'db_table': 'ZDAB',
                'ordering': ['CODE'],
            },
        ),
    ]
