# Generated by Django 5.0.6 on 2025-11-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametre', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zdab',
            name='CODE',
            field=models.CharField(help_text='3 lettres majuscules (ex: CPN, RTT, MAL)', max_length=3, unique=True, verbose_name='Code absence'),
        ),
    ]
