# Generated by Django 5.0.6 on 2025-12-12 00:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('absence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('code', models.CharField(help_text='Code interne unique', max_length=10, unique=True, verbose_name='Code entreprise')),
                ('nom', models.CharField(max_length=200, verbose_name="Nom de l'entreprise")),
                ('raison_sociale', models.CharField(blank=True, max_length=200, verbose_name='Raison sociale')),
                ('sigle', models.CharField(blank=True, max_length=20, verbose_name='Sigle')),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('pays', models.CharField(default='TOGO', max_length=100, verbose_name='Pays')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('site_web', models.URLField(blank=True, verbose_name='Site web')),
                ('rccm', models.CharField(blank=True, help_text='Registre de Commerce et du Crédit Mobilier', max_length=50, verbose_name='RCCM')),
                ('numero_impot', models.CharField(blank=True, max_length=50, verbose_name="Numéro d'impôt")),
                ('numero_cnss', models.CharField(blank=True, max_length=50, verbose_name='Numéro CNSS')),
                ('date_creation', models.DateField(blank=True, null=True, verbose_name='Date de création')),
                ('date_application_convention', models.DateField(blank=True, null=True, verbose_name="Date d'application de la convention")),
                ('actif', models.BooleanField(default=True, help_text="L'entreprise est-elle active ?", verbose_name='Actif')),
                ('logo', models.ImageField(blank=True, help_text="Logo de l'entreprise", null=True, upload_to='logos_entreprise/', verbose_name='Logo')),
                ('description', models.TextField(blank=True, help_text="Description de l'entreprise", verbose_name='Description')),
                ('configuration_conventionnelle', models.ForeignKey(blank=True, help_text="Convention collective principale de l'entreprise", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entreprises', to='absence.configurationconventionnelle', verbose_name='Convention collective applicable')),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
                'db_table': 'ENTREPRISE',
                'ordering': ['nom'],
            },
        ),
    ]
