# Generated by Django 5.0.6 on 2026-02-03 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_achats', '0001_initial'),
    ]

    operations = [
        # Ajouter le champ date_modification s'il n'existe pas (avec SQL conditionnel)
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_name = 'gestion_achats_gaccategorie'
                        AND column_name = 'date_modification'
                    ) THEN
                        ALTER TABLE gestion_achats_gaccategorie
                        ADD COLUMN date_modification TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW();
                    END IF;
                END $$;
            """,
            reverse_sql="ALTER TABLE gestion_achats_gaccategorie DROP COLUMN IF EXISTS date_modification;",
        ),

        # Ajouter le champ cree_par s'il n'existe pas
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_name = 'gestion_achats_gaccategorie'
                        AND column_name = 'cree_par_id'
                    ) THEN
                        ALTER TABLE gestion_achats_gaccategorie
                        ADD COLUMN cree_par_id UUID REFERENCES employee_zy00(uuid) ON DELETE SET NULL;
                    END IF;
                END $$;
            """,
            reverse_sql="ALTER TABLE gestion_achats_gaccategorie DROP COLUMN IF EXISTS cree_par_id;",
        ),

        # Ajouter le champ modifie_par s'il n'existe pas
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_name = 'gestion_achats_gaccategorie'
                        AND column_name = 'modifie_par_id'
                    ) THEN
                        ALTER TABLE gestion_achats_gaccategorie
                        ADD COLUMN modifie_par_id UUID REFERENCES employee_zy00(uuid) ON DELETE SET NULL;
                    END IF;
                END $$;
            """,
            reverse_sql="ALTER TABLE gestion_achats_gaccategorie DROP COLUMN IF EXISTS modifie_par_id;",
        ),
    ]
