# Generated by Django 5.0.6 on 2026-02-06 13:09

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_zyre_unique_together'),
        ('gestion_achats', '0002_add_missing_fields_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='GACParametres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seuil_validation_n2', models.DecimalField(decimal_places=2, default=Decimal('5000.00'), help_text='Montant TTC à partir duquel une validation N2 est requise (en euros)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Seuil de validation N2')),
                ('delai_livraison_defaut', models.IntegerField(default=30, help_text='Délai de livraison par défaut en jours', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Délai de livraison par défaut')),
                ('notifier_demandeur', models.BooleanField(default=True, help_text='Envoyer une notification au demandeur lors des changements de statut', verbose_name='Notifier le demandeur')),
                ('notifier_validateurs', models.BooleanField(default=True, help_text='Envoyer une notification aux validateurs lors de nouvelles demandes', verbose_name='Notifier les validateurs')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parametres_gac_modifies', to='employee.zy00', verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Paramètres GAC',
                'verbose_name_plural': 'Paramètres GAC',
            },
        ),
    ]
