# Generated by Django 5.0.6 on 2026-02-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_zyre_unique_together'),
        ('gestion_achats', '0008_gacparametres'),
    ]

    operations = [
        # Utiliser SeparateDatabaseAndState pour synchroniser l'état Django
        # avec le SQL conditionnel (la colonne siret n'existe peut-être déjà plus en base)
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Supprimer l'index sur siret s'il existe
                migrations.RunSQL(
                    sql="DROP INDEX IF EXISTS gestion_ach_siret_dafd57_idx;",
                    reverse_sql="""
                        DO $$
                        BEGIN
                            IF EXISTS (
                                SELECT 1 FROM information_schema.columns
                                WHERE table_name = 'gestion_achats_gacfournisseur'
                                AND column_name = 'siret'
                            ) THEN
                                CREATE INDEX gestion_ach_siret_dafd57_idx
                                ON gestion_achats_gacfournisseur (siret);
                            END IF;
                        END $$;
                    """,
                ),
                # Supprimer la colonne siret si elle existe
                migrations.RunSQL(
                    sql="ALTER TABLE gestion_achats_gacfournisseur DROP COLUMN IF EXISTS siret;",
                    reverse_sql="""
                        DO $$
                        BEGIN
                            IF NOT EXISTS (
                                SELECT 1 FROM information_schema.columns
                                WHERE table_name = 'gestion_achats_gacfournisseur'
                                AND column_name = 'siret'
                            ) THEN
                                ALTER TABLE gestion_achats_gacfournisseur
                                ADD COLUMN siret VARCHAR(14) UNIQUE;
                            END IF;
                        END $$;
                    """,
                ),
                # Ajouter la colonne nif si elle n'existe pas
                migrations.RunSQL(
                    sql="""
                        DO $$
                        BEGIN
                            IF NOT EXISTS (
                                SELECT 1 FROM information_schema.columns
                                WHERE table_name = 'gestion_achats_gacfournisseur'
                                AND column_name = 'nif'
                            ) THEN
                                ALTER TABLE gestion_achats_gacfournisseur
                                ADD COLUMN nif VARCHAR(10) NULL;
                            END IF;
                        END $$;
                    """,
                    reverse_sql="ALTER TABLE gestion_achats_gacfournisseur DROP COLUMN IF EXISTS nif;",
                ),
                # Modifier la valeur par défaut de pays
                migrations.RunSQL(
                    sql="ALTER TABLE gestion_achats_gacfournisseur ALTER COLUMN pays SET DEFAULT 'Togo';",
                    reverse_sql="ALTER TABLE gestion_achats_gacfournisseur ALTER COLUMN pays SET DEFAULT 'France';",
                ),
                # Ajouter l'index sur nif s'il n'existe pas
                migrations.RunSQL(
                    sql="""
                        DO $$
                        BEGIN
                            IF NOT EXISTS (
                                SELECT 1 FROM pg_indexes
                                WHERE indexname = 'gestion_ach_nif_118ebd_idx'
                            ) THEN
                                CREATE INDEX gestion_ach_nif_118ebd_idx
                                ON gestion_achats_gacfournisseur (nif);
                            END IF;
                        END $$;
                    """,
                    reverse_sql="DROP INDEX IF EXISTS gestion_ach_nif_118ebd_idx;",
                ),
            ],
            state_operations=[
                # Ces opérations mettent à jour l'état interne de Django
                # sans toucher la base de données
                migrations.RemoveIndex(
                    model_name='gacfournisseur',
                    name='gestion_ach_siret_dafd57_idx',
                ),
                migrations.RemoveField(
                    model_name='gacfournisseur',
                    name='siret',
                ),
                migrations.AddField(
                    model_name='gacfournisseur',
                    name='nif',
                    field=models.CharField(
                        blank=True,
                        help_text='9 à 10 chiffres (optionnel)',
                        max_length=10,
                        null=True,
                        verbose_name="NIF (Numéro d'Identification Fiscale)",
                    ),
                ),
                migrations.AlterField(
                    model_name='gacfournisseur',
                    name='pays',
                    field=models.CharField(
                        default='Togo',
                        max_length=100,
                        verbose_name='Pays',
                    ),
                ),
                migrations.AddIndex(
                    model_name='gacfournisseur',
                    index=models.Index(fields=['nif'], name='gestion_ach_nif_118ebd_idx'),
                ),
            ],
        ),
    ]
