# Generated by Django 5.0.6 on 2026-02-14 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_achats', '0009_remove_gacfournisseur_gestion_ach_siret_dafd57_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GACNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('lien', models.CharField(blank=True, default='', max_length=500, verbose_name='Lien')),
                ('niveau', models.CharField(choices=[('INFO', 'Information'), ('AVERTISSEMENT', 'Avertissement'), ('WARNING', 'Avertissement'), ('CRITIQUE', 'Critique'), ('ERROR', 'Erreur')], default='INFO', max_length=20, verbose_name='Niveau')),
                ('lu', models.BooleanField(default=False, verbose_name='Lu')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_lecture', models.DateTimeField(blank=True, null=True, verbose_name='Date de lecture')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_gac', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
            ],
            options={
                'verbose_name': 'Notification GAC',
                'verbose_name_plural': 'Notifications GAC',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['utilisateur', 'lu'], name='gestion_ach_utilisa_507a3a_idx'), models.Index(fields=['utilisateur', '-date_creation'], name='gestion_ach_utilisa_397d67_idx')],
            },
        ),
    ]
