# Generated by Django 5.0.6 on 2026-02-14 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_achats', '0010_ajouter_gac_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GACNotification',
        ),
    ]
