"""
Constantes pour l'application employee
Fichier : employee/constants.py
"""

# ============================================
# LISTE DES PAYS DU MONDE
# ============================================

PAYS_CHOICES = [
    ('', '-- Sélectionner un pays --'),
    ('Afghanistan', 'Afghanistan'),
    ('Afrique du Sud', 'Afrique du Sud'),
    ('Albanie', 'Albanie'),
    ('Algérie', 'Algérie'),
    ('Allemagne', 'Allemagne'),
    ('Andorre', 'Andorre'),
    ('Angola', 'Angola'),
    ('Antigua-et-Barbuda', 'Antigua-et-Barbuda'),
    ('Arabie Saoudite', 'Arabie Saoudite'),
    ('Argentine', 'Argentine'),
    ('Arménie', 'Arménie'),
    ('Australie', 'Australie'),
    ('Autriche', 'Autriche'),
    ('Azerbaïdjan', 'Azerbaïdjan'),
    ('Bahamas', 'Bahamas'),
    ('Bahreïn', 'Bahreïn'),
    ('Bangladesh', 'Bangladesh'),
    ('Barbade', 'Barbade'),
    ('Belgique', 'Belgique'),
    ('Belize', 'Belize'),
    ('Bénin', 'Bénin'),
    ('Bhoutan', 'Bhoutan'),
    ('Biélorussie', 'Biélorussie'),
    ('Birmanie', 'Birmanie'),
    ('Bolivie', 'Bolivie'),
    ('Bosnie-Herzégovine', 'Bosnie-Herzégovine'),
    ('Botswana', 'Botswana'),
    ('Brésil', 'Brésil'),
    ('Brunei', 'Brunei'),
    ('Bulgarie', 'Bulgarie'),
    ('Burkina Faso', 'Burkina Faso'),
    ('Burundi', 'Burundi'),
    ('Cambodge', 'Cambodge'),
    ('Cameroun', 'Cameroun'),
    ('Canada', 'Canada'),
    ('Cap-Vert', 'Cap-Vert'),
    ('Centrafrique', 'République Centrafricaine'),
    ('Chili', 'Chili'),
    ('Chine', 'Chine'),
    ('Chypre', 'Chypre'),
    ('Colombie', 'Colombie'),
    ('Comores', 'Comores'),
    ('Congo', 'Congo'),
    ('Congo (RDC)', 'République Démocratique du Congo'),
    ('Corée du Nord', 'Corée du Nord'),
    ('Corée du Sud', 'Corée du Sud'),
    ('Costa Rica', 'Costa Rica'),
    ('Côte d\'Ivoire', 'Côte d\'Ivoire'),
    ('Croatie', 'Croatie'),
    ('Cuba', 'Cuba'),
    ('Danemark', 'Danemark'),
    ('Djibouti', 'Djibouti'),
    ('Dominique', 'Dominique'),
    ('Égypte', 'Égypte'),
    ('Émirats Arabes Unis', 'Émirats Arabes Unis'),
    ('Équateur', 'Équateur'),
    ('Érythrée', 'Érythrée'),
    ('Espagne', 'Espagne'),
    ('Estonie', 'Estonie'),
    ('Eswatini', 'Eswatini'),
    ('États-Unis', 'États-Unis'),
    ('Éthiopie', 'Éthiopie'),
    ('Fidji', 'Fidji'),
    ('Finlande', 'Finlande'),
    ('France', 'France'),
    ('Gabon', 'Gabon'),
    ('Gambie', 'Gambie'),
    ('Géorgie', 'Géorgie'),
    ('Ghana', 'Ghana'),
    ('Grèce', 'Grèce'),
    ('Grenade', 'Grenade'),
    ('Guatemala', 'Guatemala'),
    ('Guinée', 'Guinée'),
    ('Guinée-Bissau', 'Guinée-Bissau'),
    ('Guinée Équatoriale', 'Guinée Équatoriale'),
    ('Guyana', 'Guyana'),
    ('Haïti', 'Haïti'),
    ('Honduras', 'Honduras'),
    ('Hongrie', 'Hongrie'),
    ('Inde', 'Inde'),
    ('Indonésie', 'Indonésie'),
    ('Irak', 'Irak'),
    ('Iran', 'Iran'),
    ('Irlande', 'Irlande'),
    ('Islande', 'Islande'),
    ('Israël', 'Israël'),
    ('Italie', 'Italie'),
    ('Jamaïque', 'Jamaïque'),
    ('Japon', 'Japon'),
    ('Jordanie', 'Jordanie'),
    ('Kazakhstan', 'Kazakhstan'),
    ('Kenya', 'Kenya'),
    ('Kirghizistan', 'Kirghizistan'),
    ('Kiribati', 'Kiribati'),
    ('Koweït', 'Koweït'),
    ('Laos', 'Laos'),
    ('Lesotho', 'Lesotho'),
    ('Lettonie', 'Lettonie'),
    ('Liban', 'Liban'),
    ('Liberia', 'Liberia'),
    ('Libye', 'Libye'),
    ('Liechtenstein', 'Liechtenstein'),
    ('Lituanie', 'Lituanie'),
    ('Luxembourg', 'Luxembourg'),
    ('Macédoine du Nord', 'Macédoine du Nord'),
    ('Madagascar', 'Madagascar'),
    ('Malaisie', 'Malaisie'),
    ('Malawi', 'Malawi'),
    ('Maldives', 'Maldives'),
    ('Mali', 'Mali'),
    ('Malte', 'Malte'),
    ('Maroc', 'Maroc'),
    ('Maurice', 'Maurice'),
    ('Mauritanie', 'Mauritanie'),
    ('Mexique', 'Mexique'),
    ('Micronésie', 'Micronésie'),
    ('Moldavie', 'Moldavie'),
    ('Monaco', 'Monaco'),
    ('Mongolie', 'Mongolie'),
    ('Monténégro', 'Monténégro'),
    ('Mozambique', 'Mozambique'),
    ('Namibie', 'Namibie'),
    ('Nauru', 'Nauru'),
    ('Népal', 'Népal'),
    ('Nicaragua', 'Nicaragua'),
    ('Niger', 'Niger'),
    ('Nigeria', 'Nigeria'),
    ('Norvège', 'Norvège'),
    ('Nouvelle-Zélande', 'Nouvelle-Zélande'),
    ('Oman', 'Oman'),
    ('Ouganda', 'Ouganda'),
    ('Ouzbékistan', 'Ouzbékistan'),
    ('Pakistan', 'Pakistan'),
    ('Palaos', 'Palaos'),
    ('Palestine', 'Palestine'),
    ('Panama', 'Panama'),
    ('Papouasie-Nouvelle-Guinée', 'Papouasie-Nouvelle-Guinée'),
    ('Paraguay', 'Paraguay'),
    ('Pays-Bas', 'Pays-Bas'),
    ('Pérou', 'Pérou'),
    ('Philippines', 'Philippines'),
    ('Pologne', 'Pologne'),
    ('Portugal', 'Portugal'),
    ('Qatar', 'Qatar'),
    ('Roumanie', 'Roumanie'),
    ('Royaume-Uni', 'Royaume-Uni'),
    ('Russie', 'Russie'),
    ('Rwanda', 'Rwanda'),
    ('Saint-Christophe-et-Niévès', 'Saint-Christophe-et-Niévès'),
    ('Sainte-Lucie', 'Sainte-Lucie'),
    ('Saint-Marin', 'Saint-Marin'),
    ('Saint-Vincent-et-les-Grenadines', 'Saint-Vincent-et-les-Grenadines'),
    ('Salomon', 'Salomon'),
    ('Salvador', 'Salvador'),
    ('Samoa', 'Samoa'),
    ('São Tomé-et-Principe', 'São Tomé-et-Principe'),
    ('Sénégal', 'Sénégal'),
    ('Serbie', 'Serbie'),
    ('Seychelles', 'Seychelles'),
    ('Sierra Leone', 'Sierra Leone'),
    ('Singapour', 'Singapour'),
    ('Slovaquie', 'Slovaquie'),
    ('Slovénie', 'Slovénie'),
    ('Somalie', 'Somalie'),
    ('Soudan', 'Soudan'),
    ('Soudan du Sud', 'Soudan du Sud'),
    ('Sri Lanka', 'Sri Lanka'),
    ('Suède', 'Suède'),
    ('Suisse', 'Suisse'),
    ('Suriname', 'Suriname'),
    ('Syrie', 'Syrie'),
    ('Tadjikistan', 'Tadjikistan'),
    ('Tanzanie', 'Tanzanie'),
    ('Tchad', 'Tchad'),
    ('Tchéquie', 'Tchéquie'),
    ('Thaïlande', 'Thaïlande'),
    ('Timor oriental', 'Timor oriental'),
    ('Togo', 'Togo'),
    ('Tonga', 'Tonga'),
    ('Trinité-et-Tobago', 'Trinité-et-Tobago'),
    ('Tunisie', 'Tunisie'),
    ('Turkménistan', 'Turkménistan'),
    ('Turquie', 'Turquie'),
    ('Tuvalu', 'Tuvalu'),
    ('Ukraine', 'Ukraine'),
    ('Uruguay', 'Uruguay'),
    ('Vanuatu', 'Vanuatu'),
    ('Vatican', 'Vatican'),
    ('Venezuela', 'Venezuela'),
    ('Vietnam', 'Vietnam'),
    ('Yémen', 'Yémen'),
    ('Zambie', 'Zambie'),
    ('Zimbabwe', 'Zimbabwe'),
]


# ============================================
# AUTRES CONSTANTES (SI NÉCESSAIRE)
# ============================================

# Vous pouvez ajouter d'autres listes de choix ici
# Par exemple :

SITUATION_FAMILIALE_CHOICES = [
    ('', '-- Sélectionner --'),
    ('CELIBATAIRE', 'Célibataire'),
    ('MARIE', 'Marié(e)'),
    ('DIVORCE', 'Divorcé(e)'),
    ('VEUF', 'Veuf/Veuve'),
    ('PACSE', 'Pacsé(e)'),
    ('UNION_LIBRE', 'Union libre'),
]

TYPE_IDENTITE_CHOICES = [
    ('', '-- Sélectionner --'),
    ('CNI', 'Carte Nationale d\'Identité'),
    ('PASSEPORT', 'Passeport'),
    ('ATTESTATION', 'Attestation d\'Identité'),
    ('PERMIS', 'Permis de Conduire'),
]

SEXE_CHOICES = [
    ('M', 'Masculin'),
    ('F', 'Féminin'),
]


# ============================================
# FONCTIONS UTILITAIRES (OPTIONNEL)
# ============================================

def get_pays_par_continent():
    """Retourne les pays regroupés par continent (optionnel)"""
    return {
        'Afrique': [p for p in PAYS_CHOICES if p[0] in [
            'Afrique du Sud', 'Algérie', 'Angola', 'Bénin', 'Botswana',
            'Burkina Faso', 'Burundi', 'Cameroun', 'Cap-Vert', 'Centrafrique',
            'Comores', 'Congo', 'Congo (RDC)', 'Côte d\'Ivoire', 'Djibouti',
            'Égypte', 'Érythrée', 'Eswatini', 'Éthiopie', 'Gabon', 'Gambie',
            'Ghana', 'Guinée', 'Guinée-Bissau', 'Guinée Équatoriale', 'Kenya',
            'Lesotho', 'Liberia', 'Libye', 'Madagascar', 'Malawi', 'Mali',
            'Maroc', 'Maurice', 'Mauritanie', 'Mozambique', 'Namibie', 'Niger',
            'Nigeria', 'Ouganda', 'Rwanda', 'São Tomé-et-Principe', 'Sénégal',
            'Seychelles', 'Sierra Leone', 'Somalie', 'Soudan', 'Soudan du Sud',
            'Tanzanie', 'Tchad', 'Togo', 'Tunisie', 'Zambie', 'Zimbabwe'
        ]],
        'Europe': [p for p in PAYS_CHOICES if p[0] in [
            'Albanie', 'Allemagne', 'Andorre', 'Autriche', 'Belgique',
            'Biélorussie', 'Bosnie-Herzégovine', 'Bulgarie', 'Chypre',
            'Croatie', 'Danemark', 'Espagne', 'Estonie', 'Finlande', 'France',
            'Grèce', 'Hongrie', 'Irlande', 'Islande', 'Italie', 'Lettonie',
            'Liechtenstein', 'Lituanie', 'Luxembourg', 'Macédoine du Nord',
            'Malte', 'Moldavie', 'Monaco', 'Monténégro', 'Norvège', 'Pays-Bas',
            'Pologne', 'Portugal', 'Roumanie', 'Royaume-Uni', 'Russie',
            'Saint-Marin', 'Serbie', 'Slovaquie', 'Slovénie', 'Suède', 'Suisse',
            'Tchéquie', 'Ukraine', 'Vatican'
        ]],
        # Ajoutez les autres continents si nécessaire...
    }