# Generated by Django 5.0.6 on 2025-12-12 00:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZDLOG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TABLE_NAME', models.CharField(max_length=100, verbose_name='Nom de la table')),
                ('RECORD_ID', models.CharField(max_length=100, verbose_name="Clé de l'enregistrement")),
                ('TYPE_MOUVEMENT', models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression')], max_length=10, verbose_name='Type de mouvement')),
                ('DATE_MODIFICATION', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date et heure de modification')),
                ('USER_NAME', models.CharField(blank=True, max_length=150, verbose_name="Nom d'utilisateur")),
                ('ANCIENNE_VALEUR', models.JSONField(blank=True, null=True, verbose_name='Ancienne valeur')),
                ('NOUVELLE_VALEUR', models.JSONField(blank=True, null=True, verbose_name='Nouvelle valeur')),
                ('DESCRIPTION', models.TextField(blank=True, verbose_name='Description')),
                ('IP_ADDRESS', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('USER', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Log de modification',
                'verbose_name_plural': 'Logs de modifications',
                'db_table': 'ZDLOG',
                'ordering': ['-DATE_MODIFICATION'],
                'indexes': [models.Index(fields=['TABLE_NAME', 'RECORD_ID'], name='ZDLOG_TABLE_N_707b8c_idx'), models.Index(fields=['DATE_MODIFICATION'], name='ZDLOG_DATE_MO_38f62e_idx'), models.Index(fields=['USER'], name='ZDLOG_USER_id_a4353a_idx'), models.Index(fields=['TYPE_MOUVEMENT'], name='ZDLOG_TYPE_MO_cf4636_idx')],
            },
        ),
    ]
