# Generated by Django 5.0.6 on 2026-01-26 21:44

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0002_alter_zyre_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='JRClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_client', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Code Client')),
                ('raison_sociale', models.CharField(max_length=200, verbose_name='Raison Sociale')),
                ('contact_principal', models.CharField(max_length=100, verbose_name='Contact principal')),
                ('email_contact', models.EmailField(max_length=254, verbose_name='Email contact')),
                ('telephone_contact', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('code_postal', models.CharField(blank=True, max_length=10, null=True, verbose_name='Code Postal')),
                ('ville', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville')),
                ('pays', models.CharField(default='France', max_length=50, verbose_name='Pays')),
                ('numero_tva', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro TVA')),
                ('conditions_paiement', models.TextField(blank=True, null=True, verbose_name='Conditions de paiement')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('SUSPENDU', 'Suspendu')], default='ACTIF', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['raison_sociale'],
            },
        ),
        migrations.CreateModel(
            name='JRProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code Projet')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du projet')),
                ('description', models.TextField(blank=True, null=True)),
                ('montant_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Montant total (€)')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin_prevue', models.DateField(verbose_name='Date de fin prévue')),
                ('date_fin_reelle', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('PLANIFIE', 'Planifié'), ('ACTIF', 'Actif'), ('EN_PAUSE', 'En pause'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='PLANIFIE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chef_projet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm_projets_diriges', to='employee.zy00', verbose_name='Chef de projet')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projets', to='project_management.jrclient', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JRTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code Ticket')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre du ticket')),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('priorite', models.CharField(choices=[('BASSE', 'Basse'), ('MOYENNE', 'Moyenne'), ('HAUTE', 'Haute'), ('CRITIQUE', 'Critique')], default='MOYENNE', max_length=20, verbose_name='Priorité')),
                ('statut', models.CharField(choices=[('OUVERT', 'Ouvert'), ('EN_COURS', 'En cours'), ('EN_REVue', 'En revue'), ('TERMINE', 'Terminé')], default='OUVERT', max_length=20, verbose_name='Statut')),
                ('type_ticket', models.CharField(choices=[('TACHE', 'Tâche'), ('AMELIORATION', 'Amélioration'), ('NOUVELLE_FONCTIONNALITE', 'Nouvelle fonctionnalité'), ('BUG', 'Bug')], default='TACHE', max_length=30, verbose_name='Type de ticket')),
                ('estimation_heures', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Estimation (heures)')),
                ('temps_passe', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Temps passé (heures)')),
                ('date_echeance', models.DateField(blank=True, null=True, verbose_name="Date d'échéance")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dans_backlog', models.BooleanField(default=False, verbose_name='Dans le backlog')),
                ('ordre_backlog', models.PositiveIntegerField(default=0, verbose_name='Ordre dans le backlog')),
                ('assigne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm_tickets_assignes', to='employee.zy00', verbose_name='Assigné à')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='project_management.jrproject', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JRSprint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du sprint')),
                ('description', models.TextField(blank=True, null=True)),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('statut', models.CharField(choices=[('PLANIFIE', 'Planifié'), ('ACTIF', 'Actif'), ('TERMINE', 'Terminé')], default='PLANIFIE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='project_management.jrproject', verbose_name='Projet')),
                ('tickets', models.ManyToManyField(blank=True, related_name='sprints', to='project_management.jrticket', verbose_name='Tickets du sprint')),
            ],
            options={
                'verbose_name': 'Sprint',
                'verbose_name_plural': 'Sprints',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='JRPieceJointe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fichier', models.FileField(upload_to='tickets_pieces_jointes/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png', 'gif', 'zip', 'rar'])], verbose_name='Fichier')),
                ('nom_original', models.CharField(max_length=255, verbose_name='Nom original')),
                ('taille', models.PositiveIntegerField(verbose_name='Taille (octets)')),
                ('type_mime', models.CharField(max_length=100, verbose_name='Type MIME')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.zy00', verbose_name='Uploadé par')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='project_management.jrticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Pièce jointe',
                'verbose_name_plural': 'Pièces jointes',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='JRHistorique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_changement', models.CharField(choices=[('CREATION', 'Création'), ('MODIFICATION', 'Modification'), ('STATUT', 'Changement de statut'), ('ASSIGNATION', 'Réassignation'), ('PRIORITE', 'Changement de priorité'), ('COMMENTAIRE', 'Ajout de commentaire'), ('PIECE_JOINTE', 'Ajout de pièce jointe')], max_length=30, verbose_name='Type de changement')),
                ('champ_modifie', models.CharField(blank=True, max_length=50, null=True, verbose_name='Champ modifié')),
                ('ancienne_valeur', models.TextField(blank=True, null=True, verbose_name='Ancienne valeur')),
                ('nouvelle_valeur', models.TextField(blank=True, null=True, verbose_name='Nouvelle valeur')),
                ('description', models.TextField(verbose_name='Description du changement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.zy00', verbose_name='Utilisateur')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='project_management.jrticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Historique',
                'verbose_name_plural': 'Historiques',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JRCommentaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contenu', models.TextField(verbose_name='Contenu du commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires_tickets', to='employee.zy00', verbose_name='Auteur')),
                ('mentions', models.ManyToManyField(blank=True, related_name='mentions_commentaires', to='employee.zy00', verbose_name='Mentions')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='project_management.jrticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='JRImputation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_imputation', models.DateField(verbose_name="Date d'imputation")),
                ('heures', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Heures travaillées')),
                ('minutes', models.PositiveIntegerField(default=0, verbose_name='Minutes supplémentaires')),
                ('description', models.TextField(verbose_name='Description du travail')),
                ('type_activite', models.CharField(choices=[('DEVELOPPEMENT', 'Développement'), ('ANALYSE', 'Analyse'), ('TEST', 'Test'), ('REUNION', 'Réunion'), ('DOCUMENTATION', 'Documentation'), ('SUPPORT', 'Support'), ('AUTRE', 'Autre')], default='DEVELOPPEMENT', max_length=30, verbose_name="Type d'activité")),
                ('statut_validation', models.CharField(choices=[('EN_ATTENTE', 'En attente de validation'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté')], default='EN_ATTENTE', max_length=20, verbose_name='Statut de validation')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('commentaire_validation', models.TextField(blank=True, null=True, verbose_name='Commentaire de validation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pm_imputations', to='employee.zy00', verbose_name='Employé')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm_imputations_validees', to='employee.zy00', verbose_name='Validé par')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imputations', to='project_management.jrticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Imputation de temps',
                'verbose_name_plural': 'Imputations de temps',
                'ordering': ['-date_imputation', '-created_at'],
                'unique_together': {('employe', 'ticket', 'date_imputation')},
            },
        ),
    ]
