# Generated by Django 5.0.6 on 2026-01-31 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jrticket',
            name='statut',
            field=models.CharField(choices=[('OUVERT', 'Ouvert'), ('EN_COURS', 'En cours'), ('EN_REVUE', 'En revue'), ('TERMINE', 'Terminé')], default='OUVERT', max_length=20, verbose_name='Statut'),
        ),
    ]
