# Generated by Django 5.0.6 on 2025-11-05 19:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZY00',
            fields=[
                ('matricule', models.CharField(editable=False, max_length=8, primary_key=True, serialize=False, unique=True, verbose_name='Matricule')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenoms', models.CharField(max_length=200, verbose_name='Prénom(s)')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe')),
                ('ville_naissance', models.CharField(blank=True, max_length=100, verbose_name='Ville de naissance')),
                ('pays_naissance', models.CharField(blank=True, max_length=100, verbose_name='Pays de naissance')),
                ('situation_familiale', models.CharField(blank=True, choices=[('CELIBATAIRE', 'Célibataire'), ('MARIE', 'Marié'), ('DIVORCE', 'Divorcé'), ('VEUVE', 'Veuve'), ('VEUF', 'Veuf'), ('PACSE', 'Pacsé'), ('CONCUBINAGE', 'Concubinage')], max_length=20, verbose_name='Situation familiale')),
                ('type_id', models.CharField(choices=[('CNI', 'CNI'), ('PASSEPORT', 'Passeport'), ('AUTRES', 'Autres')], max_length=20, verbose_name="Type d'identité")),
                ('numero_id', models.CharField(max_length=50, unique=True, verbose_name="Numéro d'identité")),
                ('date_validite_id', models.DateField(verbose_name='Date de validité ID')),
                ('date_expiration_id', models.DateField(verbose_name="Date d'expiration ID")),
                ('type_dossier', models.CharField(choices=[('PRE', 'Pré-embauche'), ('SAL', 'Salarié')], default='PRE', max_length=3, verbose_name='Type de dossier')),
                ('date_validation_embauche', models.DateField(blank=True, null=True, verbose_name='Date de validation embauche')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
                'db_table': 'ZY00',
            },
        ),
        migrations.CreateModel(
            name='ZYAD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rue', models.CharField(max_length=200, verbose_name='Rue')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('pays', models.CharField(max_length=100, verbose_name='Pays')),
                ('code_postal', models.CharField(max_length=10, verbose_name='Code postal')),
                ('type_adresse', models.CharField(choices=[('PRINCIPALE', 'Résidence principale'), ('SECONDAIRE', 'Résidence secondaire')], max_length=20, verbose_name="Type d'adresse")),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresses', to='employee.zy00', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Adresse',
                'verbose_name_plural': 'Adresses',
                'db_table': 'ZYAD',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='ZYAF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name="Date de début d'affectation")),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name="Date de fin d'affectation")),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='employee.zy00', verbose_name='Employé')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departement.zdpo', verbose_name='Poste')),
            ],
            options={
                'verbose_name': 'Affectation',
                'verbose_name_plural': 'Affectations',
                'db_table': 'ZYAF',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='ZYCO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contrat', models.CharField(choices=[('CDD', 'CDD'), ('CDI', 'CDI'), ('STAGE', 'Stage'), ('ALTERNANCE', 'Alternance'), ('APPRENTISSAGE', 'Apprentissage'), ('CONTRACTUELLE', 'Contractuelle'), ('VACATAIRE', 'Vacataire')], max_length=20, verbose_name='Type de contrat')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='employee.zy00', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Contrat',
                'verbose_name_plural': 'Contrats',
                'db_table': 'ZYCO',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='ZYME',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('date_debut_validite', models.DateField(verbose_name='Date de début de validité')),
                ('date_fin_validite', models.DateField(blank=True, null=True, verbose_name='Date de fin de validité')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='employee.zy00', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
                'db_table': 'ZYME',
                'ordering': ['-date_debut_validite'],
            },
        ),
        migrations.CreateModel(
            name='ZYTE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, verbose_name='Numéro de téléphone')),
                ('date_debut_validite', models.DateField(verbose_name='Date de début de validité')),
                ('date_fin_validite', models.DateField(blank=True, null=True, verbose_name='Date de fin de validité')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telephones', to='employee.zy00', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Téléphone',
                'verbose_name_plural': 'Téléphones',
                'db_table': 'ZYTE',
                'ordering': ['-date_debut_validite'],
            },
        ),
    ]
