# Generated by Django 5.0.6 on 2025-11-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zy00',
            name='actif',
            field=models.BooleanField(default=True),
        ),
    ]
