# Generated by Django 5.0.6 on 2026-01-04 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='zyre',
            unique_together=set(),
        ),
    ]
