# Generated by Django 5.0.6 on 2025-11-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_zy00_actif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zy00',
            name='actif',
        ),
        migrations.AddField(
            model_name='zy00',
            name='etat',
            field=models.CharField(choices=[('actif', 'Actif'), ('radie', 'Radié'), ('licencie', 'Licencié'), ('inactif', 'Inactif')], default='actif', max_length=20),
        ),
        migrations.AddField(
            model_name='zyad',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='zyaf',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='zyco',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='zyme',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='zyte',
            name='actif',
            field=models.BooleanField(default=True),
        ),
    ]
