# Generated by Django 5.0.6 on 2025-11-08 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_remove_zy00_actif_zy00_etat_zyad_actif_zyaf_actif_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zy00',
            name='etat',
            field=models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif')], default='actif', max_length=20),
        ),
    ]
