# Generated by Django 5.0.6 on 2025-11-09 22:03

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_zy00_etat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zy00',
            name='pays_naissance',
            field=django_countries.fields.CountryField(max_length=100, verbose_name='Pays de naissance'),
        ),
        migrations.AlterField(
            model_name='zyad',
            name='pays',
            field=django_countries.fields.CountryField(max_length=100, verbose_name='Pays'),
        ),
    ]
