# Generated by Django 5.0.6 on 2025-11-10 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_zy00_pays_naissance_alter_zyad_pays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zy00',
            name='pays_naissance',
            field=models.CharField(blank=True, max_length=100, verbose_name='Pays de naissance'),
        ),
        migrations.AlterField(
            model_name='zyad',
            name='pays',
            field=models.CharField(max_length=100, verbose_name='Pays'),
        ),
        migrations.CreateModel(
            name='ZYDO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('CV', 'CV'), ('LETTRE_MOTIVATION', 'Lettre de motivation'), ('DIPLOME', 'Diplôme'), ('ATTESTATION_FORMATION', 'Attestation de formation'), ('CERTIFICAT_TRAVAIL', 'Certificat de travail'), ('LETTRE_RECOMMANDATION', 'Lettre de recommandation'), ('CNI', "Carte Nationale d'Identité"), ('PASSEPORT', 'Passeport'), ('ACTE_NAISSANCE', 'Acte de naissance'), ('CERTIFICAT_RESIDENCE', 'Certificat de résidence'), ('RIB', 'RIB'), ('ATTESTATION_SECURITE_SOCIALE', 'Attestation sécurité sociale'), ('CERTIFICAT_MEDICAL', 'Certificat médical'), ('CONTRAT_SIGNE', 'Contrat signé'), ('ATTESTATION_ASSURANCE', "Attestation d'assurance"), ('JUSTIFICATIF_DOMICILE', 'Justificatif de domicile'), ('PHOTO_IDENTITE', "Photo d'identité"), ('AUTRES', 'Autres')], max_length=50, verbose_name='Type de document')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('fichier', models.FileField(upload_to='documents/employes/%Y/%m/', verbose_name='Fichier')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('taille_fichier', models.IntegerField(blank=True, null=True, verbose_name='Taille (octets)')),
                ('actif', models.BooleanField(default=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employee.zy00', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'ZYDO',
                'ordering': ['-date_ajout'],
            },
        ),
    ]
