# Generated by Django 5.0.6 on 2025-11-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_zy00_pays_naissance_alter_zyad_pays_zydo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zydo',
            name='actif',
            field=models.BooleanField(default=False),
        ),
    ]
