# Generated by Django 5.0.6 on 2025-11-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_alter_zydo_actif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zydo',
            name='actif',
            field=models.BooleanField(default=True),
        ),
    ]
