# Generated by Django 5.0.6 on 2025-11-11 20:28
from django.db import migrations, models
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_alter_zydo_actif'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZYDO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(
                    choices=[('CV', 'CV'), ('LETTRE_MOTIVATION', 'Lettre de motivation'), ('DIPLOME', 'Diplôme'),
                             ('ATTESTATION_FORMATION', 'Attestation de formation'),
                             ('CERTIFICAT_TRAVAIL', 'Certificat de travail'),
                             ('LETTRE_RECOMMANDATION', 'Lettre de recommandation'),
                             ('CNI', "Carte Nationale d'Identité"), ('PASSEPORT', 'Passeport'),
                             ('ACTE_NAISSANCE', 'Acte de naissance'),
                             ('CERTIFICAT_RESIDENCE', 'Certificat de résidence'), ('RIB', 'RIB'),
                             ('ATTESTATION_SECURITE_SOCIALE', 'Attestation sécurité sociale'),
                             ('CERTIFICAT_MEDICAL', 'Certificat médical'), ('CONTRAT_SIGNE', 'Contrat signé'),
                             ('ATTESTATION_ASSURANCE', "Attestation d'assurance"),
                             ('JUSTIFICATIF_DOMICILE', 'Justificatif de domicile'),
                             ('PHOTO_IDENTITE', "Photo d'identité"), ('AUTRES', 'Autres')], max_length=50,
                    verbose_name='Type de document')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('fichier', models.FileField(upload_to='documents/employes/%Y/%m/', verbose_name='Fichier')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('taille_fichier', models.IntegerField(blank=True, null=True, verbose_name='Taille (octets)')),
                ('actif', models.BooleanField(default=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents',
                                              to='employee.zy00', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'ZYDO',
                'ordering': ['-date_ajout'],
            },
        ),
    ]