# Generated by Django 5.0.6 on 2025-11-11 22:58

import employee.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_recreate_zydo'),
    ]

    operations = [
        migrations.AddField(
            model_name='zy00',
            name='photo',
            field=models.ImageField(blank=True, help_text="Photo de profil de l'employé (formats acceptés: JPG, PNG)", null=True, upload_to=employee.models.employee_photo_path, verbose_name='Photo de profil'),
        ),
    ]
