# Generated by Django 5.0.6 on 2025-11-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_zy00_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='zyad',
            name='complement',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Complément d'adresse"),
        ),
    ]
