# Generated by Django 5.0.6 on 2025-11-16 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_zyad_complement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZYFA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personne_charge', models.CharField(choices=[('ENFANT', 'Enfant'), ('CONJOINT', 'Conjoint'), ('PARENT', 'Parent'), ('AUTRE', 'Autre personne à charge')], max_length=20, verbose_name='Personne en charge')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=200, verbose_name='Prénom')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('date_debut_prise_charge', models.DateField(verbose_name='Date de début de prise en charge')),
                ('date_fin_prise_charge', models.DateField(blank=True, null=True, verbose_name='Date de fin de prise en charge')),
                ('actif', models.BooleanField(default=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnes_charge', to='employee.zy00', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Personne à charge',
                'verbose_name_plural': 'Personnes à charge',
                'db_table': 'ZYFA',
                'ordering': ['-date_debut_prise_charge'],
            },
        ),
    ]
