# Generated by Django 5.0.6 on 2025-11-18 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_zyfa'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZYNP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenoms', models.CharField(max_length=200, verbose_name='Prénom(s)')),
                ('date_debut_validite', models.DateField(verbose_name='Date de début de validité')),
                ('date_fin_validite', models.DateField(blank=True, null=True, verbose_name='Date de fin de validité')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_noms_prenoms', to='employee.zy00', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Historique nom/prénom',
                'verbose_name_plural': 'Historiques noms/prénoms',
                'db_table': 'ZYNP',
                'ordering': ['-date_debut_validite', '-date_creation'],
            },
        ),
    ]
