# Generated by Django 5.0.6 on 2025-11-18 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_zynp'),
    ]

    operations = [
        migrations.AddField(
            model_name='zy00',
            name='prenomuser',
            field=models.CharField(blank=True, help_text="Prénom utilisé pour l'authentification et l'affichage", max_length=200, verbose_name='Prénom utilisateur'),
        ),
        migrations.AddField(
            model_name='zy00',
            name='username',
            field=models.CharField(blank=True, help_text="Nom utilisé pour l'authentification et l'affichage", max_length=100, verbose_name="Nom d'utilisateur"),
        ),
    ]
