# Generated by Django 5.0.6 on 2025-11-19 20:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_zy00_prenomuser_zy00_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZYPP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=200, verbose_name='Prénom')),
                ('lien_parente', models.CharField(choices=[('CONJOINT', 'Conjoint(e)'), ('PARENT', 'Parent'), ('ENFANT', 'Enfant'), ('FRERE_SOEUR', 'Frère/Sœur'), ('AMI', 'Ami(e)'), ('COLLEGUE', 'Collègue'), ('VOISIN', 'Voisin(e)'), ('AUTRE', 'Autre')], max_length=20, verbose_name='Lien de parenté')),
                ('telephone_principal', models.CharField(max_length=20, verbose_name='Téléphone principal')),
                ('telephone_secondaire', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone secondaire')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse complète')),
                ('ordre_priorite', models.IntegerField(choices=[(1, 'Contact principal'), (2, 'Contact secondaire'), (3, 'Contact tertiaire')], default=1, verbose_name='Ordre de priorité')),
                ('remarques', models.TextField(blank=True, null=True, verbose_name='Remarques')),
                ('date_debut_validite', models.DateField(default=django.utils.timezone.now, verbose_name='Date de début de validité')),
                ('date_fin_validite', models.DateField(blank=True, null=True, verbose_name='Date de fin de validité')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnes_prevenir', to='employee.zy00', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Personne à prévenir',
                'verbose_name_plural': 'Personnes à prévenir',
                'db_table': 'ZYPP',
                'ordering': ['ordre_priorite', '-date_debut_validite'],
            },
        ),
    ]
