# Generated by Django 5.0.6 on 2025-11-19 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_zypp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZYIB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulaire_compte', models.CharField(help_text='Nom du ou des titulaires du compte', max_length=200, verbose_name='Titulaire du compte')),
                ('nom_banque', models.CharField(max_length=100, verbose_name='Nom de la banque')),
                ('code_banque', models.CharField(help_text='5 chiffres', max_length=5, verbose_name='Code banque')),
                ('code_guichet', models.CharField(help_text='5 chiffres', max_length=5, verbose_name='Code guichet')),
                ('numero_compte', models.CharField(help_text='11 caractères', max_length=11, verbose_name='Numéro de compte')),
                ('cle_rib', models.CharField(help_text='2 chiffres', max_length=2, verbose_name='Clé RIB')),
                ('iban', models.CharField(blank=True, help_text='Numéro IBAN international (max 34 caractères)', max_length=34, null=True, verbose_name='IBAN')),
                ('bic', models.CharField(blank=True, help_text='Code BIC/SWIFT (8 ou 11 caractères)', max_length=11, null=True, verbose_name='BIC/SWIFT')),
                ('type_compte', models.CharField(choices=[('COURANT', 'Compte courant'), ('EPARGNE', 'Compte épargne'), ('JOINT', 'Compte joint')], default='COURANT', max_length=20, verbose_name='Type de compte')),
                ('domiciliation', models.CharField(blank=True, help_text="Adresse complète de l'agence", max_length=200, null=True, verbose_name='Domiciliation bancaire')),
                ('date_ouverture', models.DateField(blank=True, null=True, verbose_name="Date d'ouverture du compte")),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('remarques', models.TextField(blank=True, null=True, verbose_name='Remarques')),
                ('employe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='identite_bancaire', to='employee.zy00', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Identité bancaire',
                'verbose_name_plural': 'Identités bancaires',
                'db_table': 'ZYIB',
                'ordering': ['-date_modification'],
            },
        ),
    ]
