# Generated by Django 5.0.6 on 2025-11-27 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0018_usersecurity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZYRO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CODE', models.CharField(max_length=20, unique=True, verbose_name='Code du rôle')),
                ('LIBELLE', models.CharField(max_length=100, verbose_name='Libellé du rôle')),
                ('DESCRIPTION', models.TextField(blank=True, null=True, verbose_name='Description du rôle')),
                ('PERMISSIONS', models.JSONField(blank=True, default=dict, help_text="Ex: {'can_validate_rh': True, 'can_validate_manager': True}", verbose_name='Permissions associées')),
                ('actif', models.BooleanField(default=True, verbose_name='Rôle actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rôle',
                'verbose_name_plural': 'Rôles',
                'db_table': 'ZYRO',
                'ordering': ['CODE'],
            },
        ),
        migrations.CreateModel(
            name='ZYRE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('actif', models.BooleanField(default=True, verbose_name='Attribution active')),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_crees', to='employee.zy00', verbose_name='Créé par')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles_attribues', to='employee.zy00', verbose_name='Employé')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='employee.zyro', verbose_name='Rôle')),
            ],
            options={
                'verbose_name': 'Attribution de rôle',
                'verbose_name_plural': 'Attributions de rôles',
                'db_table': 'ZYRE',
                'ordering': ['-date_debut'],
                'unique_together': {('employe', 'role', 'actif')},
            },
        ),
    ]
