# Generated by Django 5.0.6 on 2025-12-12 00:05

import absence.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('heure_debut', models.TimeField(blank=True, null=True, verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(blank=True, null=True, verbose_name='Heure de fin')),
                ('jours_ouvrables', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Jours ouvrables')),
                ('jours_calendaires', models.IntegerField(default=0, verbose_name='Jours calendaires')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_ATTENTE_MANAGER', 'En attente du manager'), ('EN_ATTENTE_RH', 'En attente des RH'), ('VALIDE', 'Validée'), ('REJETE', 'Rejetée'), ('ANNULE', 'Annulée'), ('RETOURNE', 'Retournée pour modification')], default='BROUILLON', max_length=30, verbose_name='Statut')),
                ('date_validation_manager', models.DateTimeField(blank=True, null=True, verbose_name='Date validation manager')),
                ('date_validation_rh', models.DateTimeField(blank=True, null=True, verbose_name='Date validation RH')),
                ('justificatif', models.FileField(blank=True, null=True, upload_to=absence.models.upload_justificatif, verbose_name='Justificatif')),
                ('motif', models.TextField(blank=True, help_text="Raison de l'absence", verbose_name='Motif')),
                ('commentaire_manager', models.TextField(blank=True, verbose_name='Commentaire du manager')),
                ('commentaire_rh', models.TextField(blank=True, verbose_name='Commentaire des RH')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Absence',
                'verbose_name_plural': 'Absences',
                'ordering': ['-date_debut', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AcquisitionConges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_reference', models.IntegerField(verbose_name='Année de référence')),
                ('jours_acquis', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='Jours acquis')),
                ('jours_pris', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='Jours pris')),
                ('jours_restants', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='Jours restants')),
                ('jours_report_anterieur', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='Report antérieur')),
                ('jours_report_nouveau', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='Nouveau report')),
                ('date_calcul', models.DateTimeField(auto_now_add=True, verbose_name='Date de calcul')),
                ('date_maj', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
            ],
            options={
                'verbose_name': 'Acquisition de congés',
                'verbose_name_plural': 'Acquisitions de congés',
            },
        ),
        migrations.CreateModel(
            name='ConfigurationConventionnelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la convention')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('annee_reference', models.IntegerField(verbose_name='Année de référence')),
                ('date_debut', models.DateField(verbose_name="Date de début d'effet")),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name="Date de fin d'effet")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('jours_acquis_par_mois', models.DecimalField(decimal_places=2, default=Decimal('2.5'), help_text='Nombre de jours de congé acquis par mois travaillé', max_digits=4, verbose_name='Jours acquis par mois')),
                ('duree_conges_principale', models.IntegerField(default=12, help_text='Durée minimale en jours pour les congés principaux consécutifs', verbose_name='Durée congés principale')),
                ('periode_prise_debut', models.DateField(help_text='Date de début de la période de prise des congés (ex: 1er mai)', verbose_name='Début période de prise')),
                ('periode_prise_fin', models.DateField(help_text='Date de fin de la période de prise des congés (ex: 30 avril)', verbose_name='Fin période de prise')),
                ('methode_calcul', models.CharField(choices=[('MOIS_TRAVAILLES', 'Par mois travaillés'), ('HEURES_TRAVAILLEES', 'Par heures travaillées'), ('JOURS_TRAVAILLES', 'Par jours travaillés')], default='MOIS_TRAVAILLES', max_length=20, verbose_name='Méthode de calcul')),
            ],
            options={
                'verbose_name': 'Configuration conventionnelle',
                'verbose_name_plural': 'Configurations conventionnelles',
                'ordering': ['-annee_reference'],
            },
        ),
        migrations.CreateModel(
            name='JourFerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text="Ex: Jour de l'an, Fête du travail, etc.", max_length=100, verbose_name='Nom du jour férié')),
                ('date', models.DateField(help_text='Date du jour férié', verbose_name='Date')),
                ('type_ferie', models.CharField(choices=[('LEGAL', 'Légal (Code du travail)'), ('ENTREPRISE', "Spécifique à l'entreprise")], default='LEGAL', max_length=20, verbose_name='Type de jour férié')),
                ('recurrent', models.BooleanField(default=True, help_text='Si coché, ce jour férié sera automatiquement reporté chaque année', verbose_name='Récurrent')),
                ('description', models.TextField(blank=True, help_text='Informations complémentaires', null=True, verbose_name='Description')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Jour férié',
                'verbose_name_plural': 'Jours fériés',
                'db_table': 'absence_jour_ferie',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='ParametreCalculConges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois_acquisition_min', models.IntegerField(default=1, verbose_name="Mois d'acquisition minimum")),
                ('plafond_jours_an', models.IntegerField(default=30, verbose_name='Plafond jours/an')),
                ('report_autorise', models.BooleanField(default=True, verbose_name='Report autorisé')),
                ('jours_report_max', models.IntegerField(default=15, verbose_name='Jours de report maximum')),
                ('delai_prise_report', models.IntegerField(default=365, verbose_name='Délai de prise du report (jours)')),
                ('jours_supp_anciennete', models.JSONField(default=dict, help_text='Format JSON: {"5": 1, "10": 2} = +1 jour après 5 ans, +2 après 10 ans', verbose_name='Jours supplémentaires ancienneté')),
                ('prise_compte_temps_partiel', models.BooleanField(default=True, verbose_name='Prise en compte temps partiel')),
            ],
            options={
                'verbose_name': 'Paramètre calcul congés',
                'verbose_name_plural': 'Paramètres calcul congés',
            },
        ),
        migrations.CreateModel(
            name='TypeAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('libelle', models.CharField(max_length=100, verbose_name='Libellé')),
                ('categorie', models.CharField(choices=[('CONGES_PAYES', 'Congés Payés'), ('MALADIE', 'Maladie/Accident'), ('AUTORISATION', 'Autorisation spéciale'), ('SANS_SOLDE', 'Sans solde'), ('MATERNITE', 'Maternité/Paternité'), ('FORMATIO', 'Formation'), ('MISSION', 'Mission')], max_length=20, verbose_name='Catégorie')),
                ('paye', models.BooleanField(default=True, verbose_name='Payé')),
                ('decompte_solde', models.BooleanField(default=True, help_text='Décompte du solde de congés', verbose_name='Décompte du solde')),
                ('justificatif_obligatoire', models.BooleanField(default=False, verbose_name='Justificatif obligatoire')),
                ('couleur', models.CharField(default='#3498db', help_text='Code couleur hexadécimal (#RRGGBB)', max_length=7, verbose_name='Couleur')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': "Type d'absence",
                'verbose_name_plural': "Types d'absence",
                'ordering': ['ordre', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='ValidationAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etape', models.CharField(choices=[('MANAGER', 'Validation manager'), ('RH', 'Validation RH')], max_length=20)),
                ('ordre', models.IntegerField()),
                ('decision', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('APPROUVE', 'Approuvé'), ('REJETE', 'Rejeté'), ('RETOURNE', 'Retourné pour modification')], default='EN_ATTENTE', max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': "Validation d'absence",
                'verbose_name_plural': "Validations d'absence",
                'ordering': ['absence', 'ordre'],
            },
        ),
    ]
