# Generated by Django 5.0.6 on 2025-11-23 17:04

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0017_zy00_user'),
        ('parametre', '0002_alter_zdab_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZDJF',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True, verbose_name='Date')),
                ('libelle', models.CharField(max_length=100, verbose_name='Libellé')),
                ('fixe', models.BooleanField(default=True, verbose_name='Date fixe')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Jour férié',
                'verbose_name_plural': 'Jours fériés',
                'db_table': 'ZDJF',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='ZDDA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_demande', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Numéro de demande')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('duree', models.CharField(choices=[('COMPLETE', 'Journée complète'), ('DEMI', 'Demi-journée')], default='COMPLETE', max_length=10, verbose_name='Durée')),
                ('periode', models.CharField(blank=True, choices=[('MATIN', 'Matin'), ('APRES_MIDI', 'Après-midi')], max_length=15, null=True, verbose_name='Période (si demi-journée)')),
                ('nombre_jours', models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.5'))], verbose_name='Nombre de jours')),
                ('motif', models.TextField(verbose_name='Motif de la demande')),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='absences/justificatifs/%Y/%m/', verbose_name='Justificatif')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDEE_MANAGER', 'Validée Manager'), ('VALIDEE_RH', 'Validée RH'), ('REFUSEE_MANAGER', 'Refusée Manager'), ('REFUSEE_RH', 'Refusée RH'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('validee_manager', models.BooleanField(default=False, verbose_name='Validée par le manager')),
                ('date_validation_manager', models.DateTimeField(blank=True, null=True, verbose_name='Date validation manager')),
                ('commentaire_manager', models.TextField(blank=True, null=True, verbose_name='Commentaire manager')),
                ('motif_refus_manager', models.TextField(blank=True, null=True, verbose_name='Motif refus manager')),
                ('validee_rh', models.BooleanField(default=False, verbose_name='Validée par RH')),
                ('date_validation_rh', models.DateTimeField(blank=True, null=True, verbose_name='Date validation RH')),
                ('commentaire_rh', models.TextField(blank=True, null=True, verbose_name='Commentaire RH')),
                ('motif_refus_rh', models.TextField(blank=True, null=True, verbose_name='Motif refus RH')),
                ('est_urgent', models.BooleanField(default=False, verbose_name='Demande urgente')),
                ('est_annulee', models.BooleanField(default=False, verbose_name='Annulée')),
                ('date_annulation', models.DateTimeField(blank=True, null=True, verbose_name="Date d'annulation")),
                ('motif_annulation', models.TextField(blank=True, null=True, verbose_name="Motif d'annulation")),
                ('solde_avant', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Solde avant')),
                ('solde_apres', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Solde après')),
                ('notification_envoyee_manager', models.BooleanField(default=False, verbose_name='Notification envoyée au manager')),
                ('notification_envoyee_rh', models.BooleanField(default=False, verbose_name='Notification envoyée à RH')),
                ('notification_envoyee_employe', models.BooleanField(default=False, verbose_name="Notification envoyée à l'employé")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_absence_creees', to='employee.zy00', verbose_name='Créé par')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_absence', to='employee.zy00', verbose_name='Employé')),
                ('type_absence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes', to='parametre.zdab', verbose_name="Type d'absence")),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_absence_modifiees', to='employee.zy00', verbose_name='Modifié par')),
                ('validateur_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations_manager_absence', to='employee.zy00', verbose_name='Manager validateur')),
                ('validateur_rh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations_rh_absence', to='employee.zy00', verbose_name='RH validateur')),
            ],
            options={
                'verbose_name': "Demande d'absence",
                'verbose_name_plural': "Demandes d'absence",
                'db_table': 'ZDDA',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ZDHA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATION', 'Création'), ('MODIFICATION', 'Modification'), ('VALIDATION_MANAGER', 'Validation Manager'), ('VALIDATION_RH', 'Validation RH'), ('REFUS_MANAGER', 'Refus Manager'), ('REFUS_RH', 'Refus RH'), ('ANNULATION', 'Annulation')], max_length=30, verbose_name='Action')),
                ('ancien_statut', models.CharField(blank=True, max_length=20, null=True, verbose_name='Ancien statut')),
                ('nouveau_statut', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nouveau statut')),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaire')),
                ('donnees_modifiees', models.JSONField(blank=True, null=True, verbose_name='Données modifiées')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date/Heure')),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='absence.zdda', verbose_name='Demande')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.zy00', verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Historique absence',
                'verbose_name_plural': 'Historiques absences',
                'db_table': 'ZDHA',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ZDPF',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=100, verbose_name='Libellé')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.zy00', verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Période de fermeture',
                'verbose_name_plural': 'Périodes de fermeture',
                'db_table': 'ZDPF',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='ZDSO',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('annee', models.IntegerField(verbose_name='Année')),
                ('jours_acquis', models.DecimalField(decimal_places=1, default=25.0, max_digits=5, verbose_name='Jours acquis')),
                ('jours_pris', models.DecimalField(decimal_places=1, default=0.0, max_digits=5, verbose_name='Jours pris')),
                ('jours_en_attente', models.DecimalField(decimal_places=1, default=0.0, max_digits=5, verbose_name='Jours en attente')),
                ('jours_disponibles', models.DecimalField(decimal_places=1, default=25.0, max_digits=5, verbose_name='Jours disponibles')),
                ('jours_reportes', models.DecimalField(decimal_places=1, default=0.0, max_digits=5, verbose_name='Jours reportés N-1')),
                ('rtt_acquis', models.DecimalField(decimal_places=1, default=0.0, max_digits=5, verbose_name='RTT acquis')),
                ('rtt_pris', models.DecimalField(decimal_places=1, default=0.0, max_digits=5, verbose_name='RTT pris')),
                ('rtt_disponibles', models.DecimalField(decimal_places=1, default=0.0, max_digits=5, verbose_name='RTT disponibles')),
                ('derniere_maj', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soldes_conges', to='employee.zy00', verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Solde de congés',
                'verbose_name_plural': 'Soldes de congés',
                'db_table': 'ZDSO',
                'ordering': ['-annee', 'employe'],
            },
        ),
        migrations.AddIndex(
            model_name='zdda',
            index=models.Index(fields=['employe', 'statut'], name='ZDDA_employe_87e958_idx'),
        ),
        migrations.AddIndex(
            model_name='zdda',
            index=models.Index(fields=['date_debut', 'date_fin'], name='ZDDA_date_de_ee13aa_idx'),
        ),
        migrations.AddIndex(
            model_name='zdda',
            index=models.Index(fields=['statut'], name='ZDDA_statut_b883b7_idx'),
        ),
        migrations.AddIndex(
            model_name='zdda',
            index=models.Index(fields=['created_at'], name='ZDDA_created_3a0429_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='zdso',
            unique_together={('employe', 'annee')},
        ),
    ]
