# Generated by Django 5.0.6 on 2025-11-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zdda',
            name='motif',
            field=models.TextField(blank=True, verbose_name='Motif de la demande'),
        ),
    ]
