# Generated by Django 5.0.6 on 2025-12-12 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('absence', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absences_crees', to='employee.zy00', verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='absence',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='employee.zy00', verbose_name='Employé'),
        ),
        migrations.AddField(
            model_name='absence',
            name='manager_validateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absences_validees_manager', to='employee.zy00', verbose_name='Validateur manager'),
        ),
        migrations.AddField(
            model_name='absence',
            name='rh_validateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absences_validees_rh', to='employee.zy00', verbose_name='Validateur RH'),
        ),
        migrations.AddField(
            model_name='acquisitionconges',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acquisitions_conges', to='employee.zy00'),
        ),
        migrations.AddField(
            model_name='jourferie',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jours_feries_crees', to='employee.zy00', verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='parametrecalculconges',
            name='configuration',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parametres_calcul', to='absence.configurationconventionnelle'),
        ),
        migrations.AddField(
            model_name='absence',
            name='type_absence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='absence.typeabsence', verbose_name="Type d'absence"),
        ),
        migrations.AddField(
            model_name='validationabsence',
            name='absence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations_detail', to='absence.absence'),
        ),
        migrations.AddField(
            model_name='validationabsence',
            name='validateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations_effectuees', to='employee.zy00'),
        ),
        migrations.AddIndex(
            model_name='acquisitionconges',
            index=models.Index(fields=['employe', 'annee_reference'], name='absence_acq_employe_e35447_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='acquisitionconges',
            unique_together={('employe', 'annee_reference')},
        ),
        migrations.AlterUniqueTogether(
            name='jourferie',
            unique_together={('nom', 'date')},
        ),
        migrations.AddIndex(
            model_name='absence',
            index=models.Index(fields=['employe', 'statut'], name='absence_abs_employe_5a3a7a_idx'),
        ),
        migrations.AddIndex(
            model_name='absence',
            index=models.Index(fields=['statut', 'date_debut'], name='absence_abs_statut_dd42b3_idx'),
        ),
        migrations.AddIndex(
            model_name='absence',
            index=models.Index(fields=['type_absence', 'date_debut'], name='absence_abs_type_ab_0d6d7b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='validationabsence',
            unique_together={('absence', 'etape')},
        ),
    ]
