# Generated by Django 5.0.6 on 2025-12-14 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jourferie',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='jourferie',
            name='date',
            field=models.DateField(help_text='Date du jour férié', unique=True, verbose_name='Date'),
        ),
    ]
