# Generated by Django 5.0.6 on 2025-11-23 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0002_alter_zdda_motif'),
        ('employee', '0017_zy00_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zdda',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_absence_creees', to='employee.zy00', verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='zdda',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_absence_modifiees', to='employee.zy00', verbose_name='Modifié par'),
        ),
    ]
