# Generated by Django 5.0.6 on 2025-11-30 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0003_alter_zdda_created_by_alter_zdda_updated_by'),
        ('employee', '0019_zyro_zyre'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZANO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('ABSENCE_NOUVELLE', "Nouvelle demande d'absence"), ('ABSENCE_VALIDEE_MANAGER', 'Absence validée par le manager'), ('ABSENCE_REJETEE_MANAGER', 'Absence rejetée par le manager'), ('ABSENCE_VALIDEE_RH', 'Absence validée par les RH'), ('ABSENCE_REJETEE_RH', 'Absence rejetée par les RH'), ('ABSENCE_ANNULEE', 'Absence annulée')], max_length=30, verbose_name='Type de notification')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('lien', models.CharField(blank=True, help_text="URL vers l'élément concerné", max_length=500, null=True, verbose_name='Lien associé')),
                ('lue', models.BooleanField(default=False, verbose_name='Lue')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_lecture', models.DateTimeField(blank=True, null=True, verbose_name='Date de lecture')),
                ('demande_absence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='absence.zdda', verbose_name="Demande d'absence")),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='employee.zy00', verbose_name='Destinataire')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'ZANO',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['destinataire', 'lue'], name='ZANO_destina_ccd240_idx'), models.Index(fields=['date_creation'], name='ZANO_date_cr_e22f91_idx')],
            },
        ),
    ]
