# Generated by Django 5.0.6 on 2025-12-14 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0003_alter_jourferie_unique_together_alter_jourferie_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeabsence',
            name='categorie',
            field=models.CharField(choices=[('CONGES_PAYES', 'Congés Payés'), ('MALADIE', 'Maladie/Accident'), ('AUTORISATION', 'Autorisation spéciale'), ('SANS_SOLDE', 'Sans solde'), ('MATERNITE', 'Maternité/Paternité'), ('FORMATION', 'Formation'), ('MISSION', 'Mission')], max_length=20, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='typeabsence',
            name='code',
            field=models.CharField(help_text='Code sur 3 caractères (ex: CPN, MAL, AUT)', max_length=3, unique=True, verbose_name='Code'),
        ),
        migrations.AlterModelTable(
            name='typeabsence',
            table='absence_type_absence',
        ),
    ]
