# Generated by Django 5.0.6 on 2025-12-15 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0004_alter_typeabsence_categorie_alter_typeabsence_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationconventionnelle',
            name='date_fin',
            field=models.DateField(blank=True, help_text='Laisser vide si la convention est toujours en vigueur', null=True, verbose_name="Date de fin d'effet"),
        ),
    ]
