# Generated by Django 5.0.6 on 2025-12-17 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0005_alter_configurationconventionnelle_date_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationconventionnelle',
            name='type_convention',
            field=models.CharField(choices=[('ENTREPRISE', "Convention d'entreprise"), ('PERSONNALISEE', 'Convention personnalisée')], default='ENTREPRISE', help_text="Convention d'entreprise (unique) ou personnalisée (pour employés spécifiques)", max_length=20, verbose_name='Type de convention'),
        ),
    ]
