# Generated by Django 5.0.6 on 2025-12-29 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0006_configurationconventionnelle_type_convention'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='periode_debut',
            field=models.CharField(choices=[('JOURNEE_COMPLETE', 'Journée complète'), ('MATIN', 'Matin'), ('APRES_MIDI', 'Après-midi')], default='JOURNEE_COMPLETE', max_length=20, verbose_name='Période de début'),
        ),
        migrations.AddField(
            model_name='absence',
            name='periode_fin',
            field=models.CharField(choices=[('JOURNEE_COMPLETE', 'Journée complète'), ('MATIN', 'Matin'), ('APRES_MIDI', 'Après-midi')], default='JOURNEE_COMPLETE', max_length=20, verbose_name='Période de fin'),
        ),
    ]
