# Generated by Django 5.0.6 on 2025-12-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0007_absence_periode_debut_absence_periode_fin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absence',
            name='heure_debut',
        ),
        migrations.RemoveField(
            model_name='absence',
            name='heure_fin',
        ),
        migrations.RemoveField(
            model_name='absence',
            name='periode_debut',
        ),
        migrations.RemoveField(
            model_name='absence',
            name='periode_fin',
        ),
        migrations.AddField(
            model_name='absence',
            name='periode',
            field=models.CharField(choices=[('JOURNEE_COMPLETE', 'Journée complète'), ('MATIN', 'Matin'), ('APRES_MIDI', 'Après-midi')], default='JOURNEE_COMPLETE', max_length=20, verbose_name='Période'),
        ),
    ]
