# Generated by Django 5.0.6 on 2025-12-31 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0008_remove_absence_heure_debut_remove_absence_heure_fin_and_more'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_ATTENTE_MANAGER', 'En attente du manager'), ('EN_ATTENTE_RH', 'En attente des RH'), ('VALIDE', 'Validée'), ('REJETE', 'Rejetée'), ('ANNULE', 'Annulée')], default='BROUILLON', max_length=30, verbose_name='Statut'),
        ),
        migrations.CreateModel(
            name='NotificationAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('DEMANDE_CREEE', "Nouvelle demande d'absence"), ('VALIDATION_MANAGER', 'Validation manager'), ('REJET_MANAGER', 'Rejet manager'), ('VALIDATION_RH', 'Validation RH'), ('REJET_RH', 'Rejet RH'), ('ABSENCE_ANNULEE', 'Absence annulée')], max_length=30, verbose_name='Type de notification')),
                ('message', models.TextField(verbose_name='Message')),
                ('lue', models.BooleanField(default=False, verbose_name='Notification lue')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_lecture', models.DateTimeField(blank=True, null=True, verbose_name='Date de lecture')),
                ('absence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='absence.absence', verbose_name='Absence')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_absences', to='employee.zy00', verbose_name='Destinataire')),
            ],
            options={
                'verbose_name': "Notification d'absence",
                'verbose_name_plural': "Notifications d'absence",
                'db_table': 'notification_absence',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['destinataire', 'lue'], name='notificatio_destina_584b95_idx'), models.Index(fields=['-date_creation'], name='notificatio_date_cr_29eef9_idx')],
            },
        ),
    ]
