# Generated by Django 5.0.6 on 2025-12-31 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0009_alter_absence_statut_notificationabsence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationabsence',
            name='type_notification',
            field=models.CharField(choices=[('DEMANDE_CREEE', "Nouvelle demande d'absence"), ('DEMANDE_VALIDEE_MANAGER', 'Demande validée par le manager'), ('VALIDATION_MANAGER', 'Validation manager'), ('REJET_MANAGER', 'Rejet manager'), ('VALIDATION_RH', 'Validation RH'), ('REJET_RH', 'Rejet RH'), ('ABSENCE_ANNULEE', 'Absence annulée')], max_length=30, verbose_name='Type de notification'),
        ),
    ]
