# Generated by Django 5.0.6 on 2025-12-31 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0010_alter_notificationabsence_type_notification'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationabsence',
            name='contexte',
            field=models.CharField(choices=[('EMPLOYE', "En tant qu'employé"), ('MANAGER', 'En tant que manager'), ('RH', 'En tant que RH')], default='EMPLOYE', max_length=20, verbose_name='Contexte de la notification'),
        ),
        migrations.AddIndex(
            model_name='notificationabsence',
            index=models.Index(fields=['contexte'], name='notificatio_context_76838b_idx'),
        ),
    ]
