# Generated by Django 5.0.6 on 2026-01-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0011_notificationabsence_contexte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationconventionnelle',
            name='periode_prise_fin_annee_suivante',
            field=models.BooleanField(default=False, help_text="Cochez si la période de prise se termine l'année suivante (ex: mai N → avril N+1)", verbose_name='Fin en année N+1'),
        ),
    ]
