# Generated by Django 5.0.6 on 2026-01-15 23:35
# Modified to use project_management.JRTicket instead of gestion_temps_activite.ZDTA

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0012_add_periode_fin_annee_suivante'),
        ('employee', '0002_alter_zyre_unique_together'),
        ('project_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationabsence',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AddField(
            model_name='notificationabsence',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='project_management.jrticket', verbose_name='Ticket'),
        ),
        migrations.AlterField(
            model_name='notificationabsence',
            name='absence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='absence.absence', verbose_name='Absence'),
        ),
        migrations.AlterField(
            model_name='notificationabsence',
            name='contexte',
            field=models.CharField(choices=[('EMPLOYE', "En tant qu'employé"), ('MANAGER', 'En tant que manager'), ('RH', 'En tant que RH'), ('PM', 'Project Management')], default='EMPLOYE', max_length=20, verbose_name='Contexte de la notification'),
        ),
        migrations.AlterField(
            model_name='notificationabsence',
            name='type_notification',
            field=models.CharField(choices=[('DEMANDE_CREEE', "Nouvelle demande d'absence"), ('DEMANDE_VALIDEE_MANAGER', 'Demande validée par le manager'), ('VALIDATION_MANAGER', 'Validation manager'), ('REJET_MANAGER', 'Rejet manager'), ('VALIDATION_RH', 'Validation RH'), ('REJET_RH', 'Rejet RH'), ('ABSENCE_ANNULEE', 'Absence annulée'), ('PROJET_ASSIGNE', 'Projet assigné'), ('TICKET_ASSIGNE', 'Ticket assigné'), ('TICKET_REASSIGNE', 'Ticket réassigné'), ('STATUT_PROJET_CHANGE', 'Statut de projet modifié'), ('STATUT_TICKET_CHANGE', 'Statut de ticket modifié'), ('COMMENTAIRE_TICKET', 'Nouveau commentaire sur ticket'), ('ECHEANCE_PROCHE', 'Échéance de ticket proche')], max_length=30, verbose_name='Type de notification'),
        ),
        migrations.AddIndex(
            model_name='notificationabsence',
            index=models.Index(fields=['ticket'], name='notificatio_ticket__a1b2c3_idx'),
        ),
    ]
