# Generated by Django 5.0.6 on 2026-01-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0013_alter_notificationabsence_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acquisitionconges',
            name='detail_mensuel',
            field=models.JSONField(blank=True, default=dict, help_text='Cache des acquisitions mensuelles figées', verbose_name='Détail mensuel'),
        ),
    ]
