# Generated by Django 5.0.6 on 2026-02-01 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0016_fix_ticket_fk_constraint'),
        ('project_management', '0002_alter_jrticket_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationabsence',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='project_management.jrproject', verbose_name='Projet'),
        ),
    ]
