# Generated by Django 5.0.6 on 2026-02-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0018_alter_notificationabsence_type_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationabsence',
            name='contexte',
            field=models.CharField(choices=[('EMPLOYE', "En tant qu'employé"), ('MANAGER', 'En tant que manager'), ('RH', 'En tant que RH'), ('PM', 'Project Management'), ('AUDIT', 'Conformité & Audit')], default='EMPLOYE', max_length=20, verbose_name='Contexte de la notification'),
        ),
        migrations.AlterField(
            model_name='notificationabsence',
            name='type_notification',
            field=models.CharField(choices=[('DEMANDE_CREEE', "Nouvelle demande d'absence"), ('DEMANDE_VALIDEE_MANAGER', 'Demande validée par le manager'), ('VALIDATION_MANAGER', 'Validation manager'), ('REJET_MANAGER', 'Rejet manager'), ('VALIDATION_RH', 'Validation RH'), ('REJET_RH', 'Rejet RH'), ('ABSENCE_ANNULEE', 'Absence annulée'), ('PROJET_ASSIGNE', 'Projet assigné'), ('PROJET_REASSIGNE', 'Projet réassigné'), ('TICKET_ASSIGNE', 'Ticket assigné'), ('TICKET_REASSIGNE', 'Ticket réassigné'), ('STATUT_PROJET_CHANGE', 'Statut de projet modifié'), ('STATUT_TICKET_CHANGE', 'Statut de ticket modifié'), ('COMMENTAIRE_TICKET', 'Nouveau commentaire sur ticket'), ('ECHEANCE_PROCHE', 'Échéance de ticket proche'), ('ALERTE_CONFORMITE', 'Nouvelle alerte de conformité')], max_length=30, verbose_name='Type de notification'),
        ),
    ]
