# Generated by Django 5.0.6 on 2026-02-14 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0019_alter_notificationabsence_contexte_and_more'),
        ('gestion_achats', '0011_delete_gacnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationabsence',
            name='bon_commande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='gestion_achats.gacboncommande', verbose_name='Bon de commande'),
        ),
        migrations.AddField(
            model_name='notificationabsence',
            name='budget_gac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='gestion_achats.gacbudget', verbose_name='Budget'),
        ),
        migrations.AddField(
            model_name='notificationabsence',
            name='demande_achat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='gestion_achats.gacdemandeachat', verbose_name="Demande d'achat"),
        ),
        migrations.AlterField(
            model_name='notificationabsence',
            name='contexte',
            field=models.CharField(choices=[('EMPLOYE', "En tant qu'employé"), ('MANAGER', 'En tant que manager'), ('RH', 'En tant que RH'), ('PM', 'Project Management'), ('AUDIT', 'Conformité & Audit'), ('GAC', 'Gestion des Achats')], default='EMPLOYE', max_length=20, verbose_name='Contexte de la notification'),
        ),
        migrations.AlterField(
            model_name='notificationabsence',
            name='type_notification',
            field=models.CharField(choices=[('DEMANDE_CREEE', "Nouvelle demande d'absence"), ('DEMANDE_VALIDEE_MANAGER', 'Demande validée par le manager'), ('VALIDATION_MANAGER', 'Validation manager'), ('REJET_MANAGER', 'Rejet manager'), ('VALIDATION_RH', 'Validation RH'), ('REJET_RH', 'Rejet RH'), ('ABSENCE_ANNULEE', 'Absence annulée'), ('PROJET_ASSIGNE', 'Projet assigné'), ('PROJET_REASSIGNE', 'Projet réassigné'), ('TICKET_ASSIGNE', 'Ticket assigné'), ('TICKET_REASSIGNE', 'Ticket réassigné'), ('STATUT_PROJET_CHANGE', 'Statut de projet modifié'), ('STATUT_TICKET_CHANGE', 'Statut de ticket modifié'), ('COMMENTAIRE_TICKET', 'Nouveau commentaire sur ticket'), ('ECHEANCE_PROCHE', 'Échéance de ticket proche'), ('ALERTE_CONFORMITE', 'Nouvelle alerte de conformité'), ('GAC_DEMANDE_SOUMISE', "Demande d'achat soumise"), ('GAC_DEMANDE_VALIDEE', "Demande d'achat validée"), ('GAC_DEMANDE_REFUSEE', "Demande d'achat refusée"), ('GAC_DEMANDE_ANNULEE', "Demande d'achat annulée"), ('GAC_DEMANDE_CONVERTIE', 'Demande convertie en BC'), ('GAC_BC_STATUT', 'Changement statut bon de commande'), ('GAC_BC_ANNULE', 'Bon de commande annulé'), ('GAC_RECEPTION', 'Notification réception'), ('GAC_ALERTE_BUDGET', 'Alerte budgétaire'), ('GAC_FIN_VALIDITE_BUDGET', 'Fin de validité budget'), ('GAC_RAPPEL', 'Rappel gestion achats'), ('GAC_RETARD_LIVRAISON', 'Retard de livraison')], max_length=30, verbose_name='Type de notification'),
        ),
    ]
