# Generated by Django 5.0.6 on 2026-02-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0020_notificationabsence_bon_commande_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationconventionnelle',
            name='mode_validation',
            field=models.CharField(choices=[('MANAGER_ET_RH', 'Validation manager + RH'), ('MANAGER_SEUL', 'Validation manager uniquement')], default='MANAGER_ET_RH', help_text='MANAGER_ET_RH : double validation. MANAGER_SEUL : le manager valide seul.', max_length=20, verbose_name='Mode de validation des absences'),
        ),
    ]
