# Generated by Django 5.0.6 on 2026-02-09 22:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0002_alter_zyre_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PosteTravail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du poste')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('type_poste', models.CharField(choices=[('JOURNEE', 'Poste journée'), ('SOIR', 'Poste soir'), ('NUIT', 'Poste nuit'), ('WEEKEND', 'Poste week-end'), ('SPECIAL', 'Poste spécial')], default='JOURNEE', max_length=20)),
                ('heure_debut', models.TimeField(verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(verbose_name='Heure de fin')),
                ('pause_dejeune', models.DurationField(default='00:30:00', verbose_name='Durée pause déjeuner')),
                ('taux_horaire', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Taux horaire (€)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Poste de travail',
                'verbose_name_plural': 'Postes de travail',
                'ordering': ['site', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='SiteTravail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du site')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('heure_ouverture', models.TimeField(default='08:00', verbose_name="Heure d'ouverture")),
                ('heure_fermeture', models.TimeField(default='18:00', verbose_name='Heure de fermeture')),
                ('fuseau_horaire', models.CharField(default='Europe/Paris', max_length=50, verbose_name='Fuseau horaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Site de travail',
                'verbose_name_plural': 'Sites de travail',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('titre', models.CharField(max_length=200, verbose_name='Titre du planning')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('PUBLIE', 'Publié'), ('VALIDE', 'Validé'), ('ARCHIVE', 'Archivé')], default='BROUILLON', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Planning',
                'verbose_name_plural': 'Plannings',
                'ordering': ['-date_debut', 'titre'],
            },
        ),
        migrations.CreateModel(
            name='QuartTravail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date', models.DateField(verbose_name='Date')),
                ('heure_debut', models.TimeField(verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(verbose_name='Heure de fin')),
                ('statut', models.CharField(choices=[('PLANIFIE', 'Planifié'), ('CONFIRME', 'Confirmé'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('ABSENT', 'Absent'), ('ANNULE', 'Annulé')], default='PLANIFIE', max_length=20)),
                ('heure_arrivee', models.TimeField(blank=True, null=True, verbose_name="Heure d'arrivée réelle")),
                ('heure_depart', models.TimeField(blank=True, null=True, verbose_name='Heure de départ réelle')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.zy00', verbose_name='Employé')),
                ('planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.planning', verbose_name='Planning')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.postetravail', verbose_name='Poste')),
            ],
            options={
                'verbose_name': 'Quart de travail',
                'verbose_name_plural': 'Quarts de travail',
                'ordering': ['date', 'heure_debut', 'employe'],
                'unique_together': {('planning', 'employe', 'date', 'poste')},
            },
        ),
        migrations.CreateModel(
            name='Pointage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('type_pointage', models.CharField(choices=[('ARRIVEE', 'Arrivée'), ('DEPART', 'Départ'), ('PAUSE_DEBUT', 'Début pause'), ('PAUSE_FIN', 'Fin pause')], max_length=20, verbose_name='Type de pointage')),
                ('date_heure', models.DateTimeField(verbose_name='Date et heure')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.zy00', verbose_name='Employé')),
                ('quart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planning.quarttravail', verbose_name='Quart associé')),
            ],
            options={
                'verbose_name': 'Pointage',
                'verbose_name_plural': 'Pointages',
                'ordering': ['-date_heure'],
            },
        ),
        migrations.AddField(
            model_name='postetravail',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.sitetravail', verbose_name='Site'),
        ),
    ]
