# Generated by Django 5.0.6 on 2026-02-09 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planning',
            options={'ordering': ['-created_at'], 'verbose_name': 'Planning', 'verbose_name_plural': 'Plannings'},
        ),
        migrations.AlterModelOptions(
            name='quarttravail',
            options={'ordering': ['date', 'heure_debut'], 'verbose_name': 'Quart de travail', 'verbose_name_plural': 'Quarts de travail'},
        ),
        migrations.AlterUniqueTogether(
            name='quarttravail',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='planning',
            name='REFERENCE',
            field=models.CharField(default=0, max_length=30, unique=True, verbose_name='Référence'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='planning',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='planning',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='planning',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('PUBLIE', 'Publié'), ('VALIDE', 'Validé'), ('ARCHIVE', 'Archivé')], default='BROUILLON', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='planning',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
        migrations.AlterField(
            model_name='postetravail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='postetravail',
            name='heure_debut',
            field=models.TimeField(default='09:00', verbose_name='Heure de début'),
        ),
        migrations.AlterField(
            model_name='postetravail',
            name='heure_fin',
            field=models.TimeField(default='17:00', verbose_name='Heure de fin'),
        ),
        migrations.AlterField(
            model_name='postetravail',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='postetravail',
            name='pause_dejeune',
            field=models.DurationField(default='00:30:00', verbose_name='Pause déjeuner'),
        ),
        migrations.AlterField(
            model_name='postetravail',
            name='taux_horaire',
            field=models.DecimalField(decimal_places=2, default=12.5, max_digits=6, verbose_name='Taux horaire (€)'),
        ),
        migrations.AlterField(
            model_name='postetravail',
            name='type_poste',
            field=models.CharField(choices=[('JOURNEE', 'Poste journée'), ('SOIR', 'Poste soir'), ('NUIT', 'Poste nuit'), ('WEEKEND', 'Poste week-end'), ('SPECIAL', 'Poste spécial')], default='JOURNEE', max_length=20, verbose_name='Type de poste'),
        ),
        migrations.AlterField(
            model_name='postetravail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
        migrations.AlterField(
            model_name='quarttravail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='quarttravail',
            name='statut',
            field=models.CharField(choices=[('PLANIFIE', 'Planifié'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('ABSENT', 'Absent'), ('ANNULE', 'Annulé')], default='PLANIFIE', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='quarttravail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
        migrations.AlterField(
            model_name='sitetravail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='sitetravail',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='sitetravail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
        migrations.AlterModelTable(
            name='planning',
            table='planning_planning',
        ),
        migrations.AlterModelTable(
            name='postetravail',
            table='planning_poste_travail',
        ),
        migrations.AlterModelTable(
            name='quarttravail',
            table='planning_quart_travail',
        ),
        migrations.AlterModelTable(
            name='sitetravail',
            table='planning_site_travail',
        ),
        migrations.RemoveField(
            model_name='quarttravail',
            name='heure_arrivee',
        ),
        migrations.RemoveField(
            model_name='quarttravail',
            name='heure_depart',
        ),
        migrations.RemoveField(
            model_name='quarttravail',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='quarttravail',
            name='uuid',
        ),
    ]
