# Generated by Django 5.0.6 on 2026-02-09 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0002_alter_planning_options_alter_quarttravail_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quarttravail',
            name='employe',
        ),
        migrations.RemoveField(
            model_name='quarttravail',
            name='planning',
        ),
        migrations.RemoveField(
            model_name='quarttravail',
            name='poste',
        ),
        migrations.DeleteModel(
            name='Pointage',
        ),
        migrations.DeleteModel(
            name='QuartTravail',
        ),
    ]
