# Generated by Django 5.0.6 on 2026-02-12 23:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_zyre_unique_together'),
        ('planning', '0003_remove_quarttravail_employe_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_debut', models.DateTimeField(verbose_name='Date/heure de debut')),
                ('date_fin', models.DateTimeField(verbose_name='Date/heure de fin')),
                ('type_evenement', models.CharField(choices=[('REUNION', 'Reunion'), ('FORMATION', 'Formation'), ('TACHE', 'Tache'), ('AUTRE', 'Autre')], default='REUNION', max_length=20, verbose_name='Type')),
                ('lieu', models.CharField(blank=True, max_length=200, verbose_name='Lieu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements_crees', to=settings.AUTH_USER_MODEL, verbose_name='Cree par')),
                ('employes', models.ManyToManyField(blank=True, related_name='evenements_planning', to='employee.zy00', verbose_name='Participants')),
            ],
            options={
                'verbose_name': 'Evenement',
                'verbose_name_plural': 'Evenements',
                'db_table': 'planning_evenement',
                'ordering': ['date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date', models.DateField(verbose_name='Date')),
                ('heure_debut', models.TimeField(verbose_name='Heure de debut')),
                ('heure_fin', models.TimeField(verbose_name='Heure de fin')),
                ('statut', models.CharField(choices=[('PLANIFIE', 'Planifie'), ('CONFIRME', 'Confirme'), ('EN_COURS', 'En cours'), ('TERMINE', 'Termine'), ('ANNULE', 'Annule')], default='PLANIFIE', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations_creees', to=settings.AUTH_USER_MODEL, verbose_name='Cree par')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_planning', to='employee.zy00', verbose_name='Employe')),
                ('planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='planning.planning', verbose_name='Planning')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='planning.postetravail', verbose_name='Poste de travail')),
            ],
            options={
                'verbose_name': 'Affectation',
                'verbose_name_plural': 'Affectations',
                'db_table': 'planning_affectation',
                'ordering': ['date', 'heure_debut'],
                'unique_together': {('employe', 'date', 'heure_debut')},
            },
        ),
    ]
