# Generated by Django 5.0.6 on 2026-02-13 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departement', '0002_initial'),
        ('planning', '0004_evenement_affectation'),
    ]

    operations = [
        migrations.AddField(
            model_name='planning',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plannings', to='departement.zdde', verbose_name='Département'),
        ),
    ]
