# Generated by Django 5.0.6 on 2026-01-23 14:10

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0002_alter_zyre_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFCA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('CODE', models.CharField(max_length=20, unique=True, verbose_name='Code catégorie')),
                ('LIBELLE', models.CharField(max_length=100, verbose_name='Libellé')),
                ('DESCRIPTION', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('JUSTIFICATIF_OBLIGATOIRE', models.BooleanField(default=True, verbose_name='Justificatif obligatoire')),
                ('PLAFOND_DEFAUT', models.DecimalField(blank=True, decimal_places=2, help_text='Montant maximum par dépense (optionnel)', max_digits=10, null=True, verbose_name='Plafond par défaut')),
                ('ICONE', models.CharField(blank=True, help_text="Classe CSS de l'icône (ex: fa-car, fa-utensils)", max_length=50, null=True, verbose_name='Icône')),
                ('STATUT', models.BooleanField(default=True, verbose_name='Actif')),
                ('ORDRE', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('UPDATED_AT', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catégorie de frais',
                'verbose_name_plural': 'Catégories de frais',
                'db_table': 'frais_categorie',
                'ordering': ['ORDRE', 'LIBELLE'],
            },
        ),
        migrations.CreateModel(
            name='NFNF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('REFERENCE', models.CharField(max_length=30, unique=True, verbose_name='Référence')),
                ('PERIODE_DEBUT', models.DateField(verbose_name='Début de période')),
                ('PERIODE_FIN', models.DateField(verbose_name='Fin de période')),
                ('OBJET', models.CharField(blank=True, max_length=200, null=True, verbose_name='Objet/Mission')),
                ('STATUT', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMIS', 'Soumis'), ('EN_VALIDATION', 'En validation'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté'), ('REMBOURSE', 'Remboursé'), ('ANNULE', 'Annulé')], default='BROUILLON', max_length=20, verbose_name='Statut')),
                ('MONTANT_TOTAL', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Montant total')),
                ('MONTANT_VALIDE', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Montant validé')),
                ('MONTANT_REMBOURSE', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Montant remboursé')),
                ('DATE_SOUMISSION', models.DateTimeField(blank=True, null=True, verbose_name='Date de soumission')),
                ('DATE_VALIDATION', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('COMMENTAIRE_VALIDATION', models.TextField(blank=True, null=True, verbose_name='Commentaire de validation')),
                ('DATE_REMBOURSEMENT', models.DateField(blank=True, null=True, verbose_name='Date de remboursement')),
                ('REFERENCE_PAIEMENT', models.CharField(blank=True, max_length=50, null=True, verbose_name='Référence de paiement')),
                ('CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('UPDATED_AT', models.DateTimeField(auto_now=True)),
                ('CREATED_BY', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_frais_creees', to='employee.zy00', verbose_name='Créé par')),
                ('EMPLOYE', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes_frais', to='employee.zy00', verbose_name='Employé')),
                ('VALIDEUR', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_frais_validees', to='employee.zy00', verbose_name='Valideur')),
            ],
            options={
                'verbose_name': 'Note de frais',
                'verbose_name_plural': 'Notes de frais',
                'db_table': 'frais_note_frais',
                'ordering': ['-CREATED_AT'],
                'permissions': [('can_validate_note_frais', 'Peut valider les notes de frais'), ('can_process_remboursement', 'Peut traiter les remboursements'), ('can_view_all_notes_frais', 'Peut voir toutes les notes de frais')],
            },
        ),
        migrations.CreateModel(
            name='NFLF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('DATE_DEPENSE', models.DateField(verbose_name='Date de la dépense')),
                ('DESCRIPTION', models.CharField(max_length=255, verbose_name='Description')),
                ('MONTANT', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant')),
                ('DEVISE', models.CharField(default='XOF', max_length=3, verbose_name='Devise')),
                ('TAUX_CHANGE', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=10, verbose_name='Taux de change')),
                ('MONTANT_CONVERTI', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant converti (XOF)')),
                ('JUSTIFICATIF', models.FileField(blank=True, null=True, upload_to='frais/justificatifs/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Justificatif')),
                ('NUMERO_FACTURE', models.CharField(blank=True, max_length=50, null=True, verbose_name='N° facture/reçu')),
                ('STATUT_LIGNE', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('COMMENTAIRE_REJET', models.TextField(blank=True, null=True, verbose_name='Motif de rejet')),
                ('CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('UPDATED_AT', models.DateTimeField(auto_now=True)),
                ('CATEGORIE', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_frais', to='frais.nfca', verbose_name='Catégorie')),
                ('NOTE_FRAIS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='frais.nfnf', verbose_name='Note de frais')),
            ],
            options={
                'verbose_name': 'Ligne de frais',
                'verbose_name_plural': 'Lignes de frais',
                'db_table': 'frais_ligne_frais',
                'ordering': ['DATE_DEPENSE'],
            },
        ),
        migrations.CreateModel(
            name='NFAV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('REFERENCE', models.CharField(max_length=30, unique=True, verbose_name='Référence')),
                ('MONTANT_DEMANDE', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1'))], verbose_name='Montant demandé')),
                ('MONTANT_APPROUVE', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Montant approuvé')),
                ('MOTIF', models.TextField(verbose_name='Motif de la demande')),
                ('DATE_MISSION_DEBUT', models.DateField(blank=True, null=True, verbose_name='Date début mission')),
                ('DATE_MISSION_FIN', models.DateField(blank=True, null=True, verbose_name='Date fin mission')),
                ('STATUT', models.CharField(choices=[('DEMANDE', 'Demandée'), ('APPROUVE', 'Approuvée'), ('VERSE', 'Versée'), ('REGULARISE', 'Régularisée'), ('ANNULE', 'Annulée')], default='DEMANDE', max_length=20, verbose_name='Statut')),
                ('DATE_APPROBATION', models.DateTimeField(blank=True, null=True, verbose_name="Date d'approbation")),
                ('COMMENTAIRE_APPROBATION', models.TextField(blank=True, null=True, verbose_name='Commentaire')),
                ('DATE_VERSEMENT', models.DateField(blank=True, null=True, verbose_name='Date de versement')),
                ('REFERENCE_VERSEMENT', models.CharField(blank=True, max_length=50, null=True, verbose_name='Référence versement')),
                ('MONTANT_REGULARISE', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Montant régularisé')),
                ('DATE_REGULARISATION', models.DateField(blank=True, null=True, verbose_name='Date de régularisation')),
                ('CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('UPDATED_AT', models.DateTimeField(auto_now=True)),
                ('APPROBATEUR', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avances_approuvees', to='employee.zy00', verbose_name='Approbateur')),
                ('CREATED_BY', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avances_creees', to='employee.zy00', verbose_name='Créé par')),
                ('EMPLOYE', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avances_frais', to='employee.zy00', verbose_name='Employé')),
                ('NOTE_FRAIS', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avances', to='frais.nfnf', verbose_name='Note de frais de régularisation')),
            ],
            options={
                'verbose_name': 'Avance sur frais',
                'verbose_name_plural': 'Avances sur frais',
                'db_table': 'frais_avance',
                'ordering': ['-CREATED_AT'],
                'permissions': [('can_approve_avance', 'Peut approuver les avances'), ('can_process_versement', 'Peut traiter les versements'), ('can_view_all_avances', 'Peut voir toutes les avances')],
            },
        ),
        migrations.CreateModel(
            name='NFPL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('GRADE', models.CharField(blank=True, help_text='Laisser vide pour appliquer à tous', max_length=50, null=True, verbose_name='Grade/Catégorie employé')),
                ('MONTANT_JOURNALIER', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Plafond journalier')),
                ('MONTANT_MENSUEL', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Plafond mensuel')),
                ('MONTANT_PAR_DEPENSE', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Plafond par dépense')),
                ('DATE_DEBUT', models.DateField(verbose_name='Date de début')),
                ('DATE_FIN', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('STATUT', models.BooleanField(default=True, verbose_name='Actif')),
                ('CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('UPDATED_AT', models.DateTimeField(auto_now=True)),
                ('CATEGORIE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plafonds', to='frais.nfca', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Plafond de frais',
                'verbose_name_plural': 'Plafonds de frais',
                'db_table': 'frais_plafond',
                'ordering': ['-DATE_DEBUT'],
            },
        ),
    ]
