# Generated by Django 5.0.6 on 2026-01-24 12:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0002_alter_zyre_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='AURC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('CODE', models.CharField(max_length=30, unique=True, verbose_name='Code de la règle')),
                ('LIBELLE', models.CharField(max_length=200, verbose_name='Libellé')),
                ('DESCRIPTION', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('TYPE_REGLE', models.CharField(choices=[('CONTRAT', 'Contrat'), ('DOCUMENT', 'Document'), ('FORMATION', 'Formation'), ('VISITE_MEDICALE', 'Visite médicale'), ('CONGE', 'Congé'), ('MATERIEL', 'Matériel'), ('AUTRE', 'Autre')], max_length=20, verbose_name='Type de règle')),
                ('SEVERITE', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Avertissement'), ('CRITICAL', 'Critique')], default='WARNING', max_length=20, verbose_name='Sévérité')),
                ('FREQUENCE_VERIFICATION', models.CharField(choices=[('QUOTIDIEN', 'Quotidien'), ('HEBDOMADAIRE', 'Hebdomadaire'), ('MENSUEL', 'Mensuel')], default='QUOTIDIEN', max_length=20, verbose_name='Fréquence de vérification')),
                ('JOURS_AVANT_EXPIRATION', models.PositiveIntegerField(default=30, help_text="Nombre de jours avant expiration pour déclencher l'alerte", verbose_name='Jours avant expiration')),
                ('PARAMETRES', models.JSONField(blank=True, help_text='Configuration JSON supplémentaire', null=True, verbose_name='Paramètres additionnels')),
                ('NOTIFIER_EMPLOYE', models.BooleanField(default=False, verbose_name="Notifier l'employé")),
                ('NOTIFIER_MANAGER', models.BooleanField(default=True, verbose_name='Notifier le manager')),
                ('NOTIFIER_RH', models.BooleanField(default=True, verbose_name='Notifier les RH')),
                ('EMAILS_SUPPLEMENTAIRES', models.TextField(blank=True, help_text='Un email par ligne', null=True, verbose_name='Emails supplémentaires')),
                ('STATUT', models.BooleanField(default=True, verbose_name='Actif')),
                ('CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('UPDATED_AT', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Règle de conformité',
                'verbose_name_plural': 'Règles de conformité',
                'db_table': 'audit_regle_conformite',
                'ordering': ['TYPE_REGLE', 'CODE'],
            },
        ),
        migrations.CreateModel(
            name='AURA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('REFERENCE', models.CharField(max_length=30, unique=True, verbose_name='Référence')),
                ('TITRE', models.CharField(max_length=200, verbose_name='Titre du rapport')),
                ('TYPE_RAPPORT', models.CharField(choices=[('CONFORMITE', 'Rapport de conformité'), ('ACTIVITE', "Rapport d'activité"), ('LOGS', 'Rapport des logs'), ('ALERTES', 'Rapport des alertes'), ('CONTRATS', 'Rapport des contrats'), ('DOCUMENTS', 'Rapport des documents'), ('PERSONNALISE', 'Rapport personnalisé')], max_length=20, verbose_name='Type de rapport')),
                ('FORMAT', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('CSV', 'CSV')], default='PDF', max_length=10, verbose_name='Format')),
                ('STATUT', models.CharField(choices=[('EN_COURS', 'En cours de génération'), ('TERMINE', 'Terminé'), ('ERREUR', 'Erreur')], default='EN_COURS', max_length=20, verbose_name='Statut')),
                ('DATE_DEBUT', models.DateField(verbose_name='Date de début')),
                ('DATE_FIN', models.DateField(verbose_name='Date de fin')),
                ('FILTRES', models.JSONField(blank=True, null=True, verbose_name='Filtres appliqués')),
                ('FICHIER', models.FileField(blank=True, null=True, upload_to='audit/rapports/%Y/%m/', verbose_name='Fichier')),
                ('TAILLE_FICHIER', models.PositiveIntegerField(blank=True, null=True, verbose_name='Taille du fichier (bytes)')),
                ('NB_ENREGISTREMENTS', models.PositiveIntegerField(default=0, verbose_name="Nombre d'enregistrements")),
                ('RESUME', models.JSONField(blank=True, null=True, verbose_name='Résumé statistique')),
                ('DATE_GENERATION', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de génération')),
                ('MESSAGE_ERREUR', models.TextField(blank=True, null=True, verbose_name="Message d'erreur")),
                ('CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('UPDATED_AT', models.DateTimeField(auto_now=True)),
                ('GENERE_PAR', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_generes', to='employee.zy00', verbose_name='Généré par')),
            ],
            options={
                'verbose_name': "Rapport d'audit",
                'verbose_name_plural': "Rapports d'audit",
                'db_table': 'audit_rapport',
                'ordering': ['-DATE_GENERATION'],
            },
        ),
        migrations.CreateModel(
            name='AUAL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('REFERENCE', models.CharField(max_length=30, unique=True, verbose_name='Référence')),
                ('TYPE_ALERTE', models.CharField(choices=[('CONTRAT', 'Contrat'), ('DOCUMENT', 'Document'), ('FORMATION', 'Formation'), ('VISITE_MEDICALE', 'Visite médicale'), ('CONGE', 'Congé'), ('MATERIEL', 'Matériel'), ('AUTRE', 'Autre')], max_length=20, verbose_name="Type d'alerte")),
                ('TITRE', models.CharField(max_length=255, verbose_name='Titre')),
                ('DESCRIPTION', models.TextField(verbose_name='Description')),
                ('PRIORITE', models.CharField(choices=[('BASSE', 'Basse'), ('MOYENNE', 'Moyenne'), ('HAUTE', 'Haute'), ('CRITIQUE', 'Critique')], default='MOYENNE', max_length=20, verbose_name='Priorité')),
                ('STATUT', models.CharField(choices=[('NOUVEAU', 'Nouveau'), ('EN_COURS', 'En cours de traitement'), ('RESOLU', 'Résolu'), ('IGNORE', 'Ignoré'), ('EXPIRE', 'Expiré')], default='NOUVEAU', max_length=20, verbose_name='Statut')),
                ('TABLE_REFERENCE', models.CharField(blank=True, max_length=100, null=True, verbose_name='Table de référence')),
                ('RECORD_ID', models.CharField(blank=True, max_length=100, null=True, verbose_name="ID de l'enregistrement")),
                ('DATE_DETECTION', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de détection')),
                ('DATE_ECHEANCE', models.DateField(blank=True, null=True, verbose_name="Date d'échéance")),
                ('DATE_RESOLUTION', models.DateTimeField(blank=True, null=True, verbose_name='Date de résolution')),
                ('COMMENTAIRE_RESOLUTION', models.TextField(blank=True, null=True, verbose_name='Commentaire de résolution')),
                ('NOTIFICATION_ENVOYEE', models.BooleanField(default=False, verbose_name='Notification envoyée')),
                ('DATE_NOTIFICATION', models.DateTimeField(blank=True, null=True, verbose_name='Date de notification')),
                ('CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('UPDATED_AT', models.DateTimeField(auto_now=True)),
                ('ASSIGNE_A', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes_assignees', to='employee.zy00', verbose_name='Assigné à')),
                ('EMPLOYE', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertes_conformite', to='employee.zy00', verbose_name='Employé concerné')),
                ('RESOLU_PAR', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes_resolues', to='employee.zy00', verbose_name='Résolu par')),
                ('REGLE', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes', to='audit.aurc', verbose_name='Règle de conformité')),
            ],
            options={
                'verbose_name': 'Alerte de conformité',
                'verbose_name_plural': 'Alertes de conformité',
                'db_table': 'audit_alerte',
                'ordering': ['-DATE_DETECTION'],
                'indexes': [models.Index(fields=['STATUT', 'PRIORITE'], name='audit_alert_STATUT_06026b_idx'), models.Index(fields=['TYPE_ALERTE'], name='audit_alert_TYPE_AL_e0a28d_idx'), models.Index(fields=['EMPLOYE'], name='audit_alert_EMPLOYE_347465_idx'), models.Index(fields=['DATE_ECHEANCE'], name='audit_alert_DATE_EC_62a33c_idx')],
            },
        ),
    ]
