"""
Django settings for HR_ONIAN project.

Generated by 'django-admin startproject' using Django 4.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os
from pathlib import Path
from django.urls import reverse_lazy

# Configuration WeasyPrint pour macOS
# Ces chemins permettent à WeasyPrint de trouver les bibliothèques système installées par Homebrew
if os.path.exists('/opt/homebrew/lib'):
    # macOS avec Apple Silicon (M1/M2)
    os.environ['DYLD_FALLBACK_LIBRARY_PATH'] = '/opt/homebrew/lib'
elif os.path.exists('/usr/local/lib'):
    # macOS avec Intel
    os.environ['DYLD_FALLBACK_LIBRARY_PATH'] = '/usr/local/lib'

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&v(=w-yis!oj=9im0=-i(ii#b!pr(b(ncf!b#h921s$%-+92@#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'employee',
    'departement',
    'core',
    'absence',
    'entreprise',
    'frais',
    'materiel',
    'audit',
    'project_management',
    'gestion_achats',
    'planning',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.CurrentRequestMiddleware',
    'core.middleware.PermissionDeniedMiddleware',
    'employee.middleware.LoginRequiredMiddleware',
    'employee.middleware.ContratExpirationMiddleware',
]

# URLs exemptées de l'authentification (en plus des URLs par défaut)
LOGIN_EXEMPT_URLS = [
    r'^/api/public/',  # API publiques si nécessaire
]

ROOT_URLCONF = 'HR_ONIAN.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'absence.context_processors.notifications_absences',
                'core.context_processors.notifications_unifiees',
            ],
        },
    },
]

WSGI_APPLICATION = 'HR_ONIAN.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'hrapp',
        'USER': 'hr',  # ← Vérifiez ce nom
        'PASSWORD': '12345',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'
APPEND_SLASH = True
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]
# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# settings.py

# Configuration pour les fichiers media
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Taille maximale des fichiers uploadés (optionnel)
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10 Mo
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10 Mo

# URLs pour les pages d'erreur
handler404 = 'employee.error_handlers.handler404'
handler500 = 'employee.error_handlers.handler500'
handler403 = 'employee.error_handlers.handler403'
handler400 = 'employee.error_handlers.handler400'

# Configuration d'authentification
LOGIN_URL = reverse_lazy('login')  # Utilise le nom de l'URL
#LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'  # ← CHANGEMENT ICI
LOGOUT_REDIRECT_URL = '/login/'

# Configuration pour forcer la redirection vers votre login



# Durée de session (optionnel)
SESSION_COOKIE_AGE = 3600  # 1 heure en secondes
SESSION_SAVE_EVERY_REQUEST = True  # Renouveler la session à chaque requête


# ============================================
# CONFIGURATION EMAIL
# ============================================
# Sécurité des connexions
LOGIN_ATTEMPTS_LIMIT = 3
ACCOUNT_LOCKOUT_DURATION = 24  # heures


DEFAULT_FROM_EMAIL = 'ONIAN-EasyM <noreply@hronian.local>'

# URL du site pour les emails
SITE_URL = 'http://127.0.0.1:8000'  # Pour le développement
# SITE_URL = 'https://votre-domaine.com'  # Pour la production
# Configuration email (assurez-vous d'avoir ces settings)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # Pour le développement
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  # Pour la production
# Si vous utilisez SMTP, configurez ces paramètres :
# EMAIL_HOST = 'votre-smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'votre-email@gmail.com'
# EMAIL_HOST_PASSWORD = 'votre-mot-de-passe'
# DEFAULT_FROM_EMAIL = 'ONIAN-EasyM <noreply@onian-easym.com>'
