# Generated by Django 5.0.6 on 2025-12-12 00:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZDDE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CODE', models.CharField(help_text='3 lettres majuscules (ex: ABC)', max_length=3, unique=True, verbose_name='Code département')),
                ('LIBELLE', models.CharField(max_length=100, verbose_name='Libellé du département')),
                ('STATUT', models.BooleanField(default=True, verbose_name='Statut actif')),
                ('DATEDEB', models.DateField(default=django.utils.timezone.now, verbose_name='Date de début de validité')),
                ('DATEFIN', models.DateField(blank=True, help_text='Laisser vide si date non définie', null=True, verbose_name='Date de fin de validité')),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
                'db_table': 'ZDDE',
            },
        ),
        migrations.CreateModel(
            name='ZDPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CODE', models.CharField(help_text='6 caractères alphanumériques (ex: PST001)', max_length=6, unique=True, verbose_name='Code poste')),
                ('LIBELLE', models.CharField(max_length=100, verbose_name='Libellé du poste')),
                ('STATUT', models.BooleanField(default=True, verbose_name='Statut actif')),
                ('DATEDEB', models.DateField(default=django.utils.timezone.now, verbose_name='Date de début de validité')),
                ('DATEFIN', models.DateField(blank=True, help_text='Laisser vide si date non définie', null=True, verbose_name='Date de fin de validité')),
                ('DEPARTEMENT', models.ForeignKey(help_text='Département auquel appartient le poste', on_delete=django.db.models.deletion.PROTECT, related_name='postes', to='departement.zdde', verbose_name='Département')),
            ],
            options={
                'verbose_name': 'Poste',
                'verbose_name_plural': 'Postes',
                'db_table': 'ZDPO',
                'ordering': ['CODE'],
            },
        ),
        migrations.CreateModel(
            name='ZYMA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(help_text="Date à laquelle l'employé devient manager du département", verbose_name='Date de début de gestion')),
                ('date_fin', models.DateField(blank=True, help_text="Date à laquelle l'employé n'est plus manager (laisser vide si toujours en poste)", null=True, verbose_name='Date de fin de gestion')),
                ('actif', models.BooleanField(default=True, verbose_name='Manager actif')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='departement.zdde', verbose_name='Département')),
            ],
            options={
                'verbose_name': 'Manager de département',
                'verbose_name_plural': 'Managers de département',
                'db_table': 'ZYMA',
                'ordering': ['-date_debut', 'departement__LIBELLE'],
            },
        ),
    ]
