# Generated by Django 5.0.6 on 2025-10-27 20:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZDDE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CODE', models.CharField(max_length=3, unique=True, verbose_name='Code département')),
                ('LIBELLE', models.CharField(max_length=100, verbose_name='Libellé du département')),
                ('STATUT', models.BooleanField(default=True, verbose_name='Statut actif')),
                ('DATEDEB', models.DateField(default=django.utils.timezone.now, verbose_name='Date de début de validité')),
                ('DATEFIN', models.DateField(blank=True, null=True, verbose_name='Date de fin de validité')),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
                'db_table': 'ZDDE',
            },
        ),
    ]
