# Generated by Django 5.0.6 on 2025-10-27 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zdde',
            name='CODE',
            field=models.CharField(help_text='3 lettres majuscules (ex: ABC)', max_length=3, unique=True, verbose_name='Code département'),
        ),
        migrations.AlterField(
            model_name='zdde',
            name='DATEFIN',
            field=models.DateField(default=datetime.date(2999, 12, 31), help_text='31/12/2999 si non renseigné', verbose_name='Date de fin de validité'),
        ),
    ]
