# Generated by Django 5.0.6 on 2025-11-17 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departement', '0001_initial'),
        ('employee', '0012_zyfa'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZYMA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(help_text="Date à laquelle l'employé devient manager du département", verbose_name='Date de début de gestion')),
                ('date_fin', models.DateField(blank=True, help_text="Date à laquelle l'employé n'est plus manager (laisser vide si toujours en poste)", null=True, verbose_name='Date de fin de gestion')),
                ('actif', models.BooleanField(default=True, verbose_name='Manager actif')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='departement.zdde', verbose_name='Département')),
                ('employe', models.ForeignKey(help_text='Employé désigné comme manager du département', on_delete=django.db.models.deletion.CASCADE, related_name='managements', to='employee.zy00', verbose_name='Manager')),
            ],
            options={
                'verbose_name': 'Manager de département',
                'verbose_name_plural': 'Managers de département',
                'db_table': 'ZYMA',
                'ordering': ['-date_debut', 'departement__LIBELLE'],
            },
        ),
        migrations.AddConstraint(
            model_name='zyma',
            constraint=models.UniqueConstraint(condition=models.Q(('date_fin__isnull', True)), fields=('departement',), name='unique_manager_actif_par_departement'),
        ),
    ]
