# Generated by Django 5.0.6 on 2025-12-12 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departement', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zyma',
            name='employe',
            field=models.ForeignKey(help_text='Employé désigné comme manager du département', on_delete=django.db.models.deletion.CASCADE, related_name='managements', to='employee.zy00', verbose_name='Manager'),
        ),
        migrations.AddConstraint(
            model_name='zyma',
            constraint=models.UniqueConstraint(condition=models.Q(('date_fin__isnull', True)), fields=('departement',), name='unique_manager_actif_par_departement'),
        ),
    ]
