# Generated by Django 5.0.6 on 2025-10-31 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zdde',
            name='DATEFIN',
            field=models.DateField(blank=True, help_text='Laisser vide si date non définie', null=True, verbose_name='Date de fin de validité'),
        ),
    ]
