# Generated by Django 5.0.6 on 2025-11-01 14:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departement', '0002_alter_zdde_datefin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZDPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CODE', models.CharField(help_text='5 caractères alphanumériques (ex: DEV01)', max_length=5, unique=True, verbose_name='Code poste')),
                ('LIBELLE', models.CharField(max_length=100, verbose_name='Libellé du poste')),
                ('STATUT', models.BooleanField(default=True, verbose_name='Statut actif')),
                ('DATEDEB', models.DateField(default=django.utils.timezone.now, verbose_name='Date de début de validité')),
                ('DATEFIN', models.DateField(blank=True, help_text='Laisser vide si date non définie', null=True, verbose_name='Date de fin de validité')),
                ('DEPARTEMENT', models.ForeignKey(help_text='Département auquel appartient le poste', on_delete=django.db.models.deletion.PROTECT, related_name='postes', to='departement.zdde', verbose_name='Département')),
            ],
            options={
                'verbose_name': 'Poste',
                'verbose_name_plural': 'Postes',
                'db_table': 'ZDPO',
                'ordering': ['CODE'],
            },
        ),
    ]
