# Generated by Django 5.0.6 on 2025-11-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departement', '0003_zdpo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zdpo',
            name='CODE',
            field=models.CharField(help_text='5 caractères alphanumériques (ex: DEV01)', max_length=6, unique=True, verbose_name='Code poste'),
        ),
    ]
